'use client';

import {useId,useMemo,useRef,useState} from 'react';
import {
  ArrowDownUp,ArrowLeft,Check,ChevronDown,CircleDollarSign,Download,Eye,FileUp,Filter,
  Layers3,Minus,PenLine,Plus,Search,Share2,ShoppingBag,SlidersHorizontal,Star,Upload,X
} from 'lucide-react';
import type {CloudConfig,Session} from '../lib/cloud';
import type {Collection,Item,Store as StoreData} from '../lib/model';
import {itemLibraryLine,money,validStore} from '../lib/model';
import {marketQuery,variantKey} from '../lib/market';
import {DesktopCommunitySync,DesktopProfile,DesktopSocial,DesktopWishlist} from './DesktopCommunity';

type View='home'|'portfolio'|'search'|'wishlist'|'social'|'profile';
type SearchScreen='filters'|'sets'|'set';
type RangeKey='1D'|'7D'|'1M'|'3M'|'6M'|'MAX';
type CategoryGroup={key:string;rawName:string;name:string;items:Item[];cover:string};
type SetGroup={key:string;rawName:string;name:string;items:Item[];cover:string;collectionId?:string};
type EditTarget={kind:'category';key:string;rawName:string;name:string}|{kind:'set';key:string;rawName:string;name:string;collectionId?:string}|{kind:'product';itemId:string};

type Props={status:string;profileName:string;data:StoreData;update:(next:StoreData)=>void;config:CloudConfig|null;session:Session|null};

const ranges:RangeKey[]=['1D','7D','1M','3M','6M','MAX'];
const sortOptions=['Price: Low to High','Price: High to Low','Name: A to Z','Name: Z to A','Newest Added'];
const nowIso=()=>new Date().toISOString();
const slug=(v:string)=>v.toLowerCase().trim().replace(/[^a-z0-9]+/g,'-').replace(/^-|-$/g,'');
const categoryKey=(name:string)=>`mobile-category::${slug(name)}`;
const setKey=(category:string,name:string)=>`mobile-set::${slug(category)}::${slug(name)}`;
function groupMeta(data:StoreData,key:string){return data.libraryGroups?.[key]||{}}
function groupName(data:StoreData,key:string,fallback:string){return groupMeta(data,key).name?.trim()||fallback}
function groupCover(data:StoreData,key:string){return groupMeta(data,key).coverImage||''}
function itemCollection(data:StoreData,item:Item){return data.collections.find(c=>c.id===item.collectionId)}
function itemCategory(data:StoreData,item:Item){return itemLibraryLine(item,itemCollection(data,item))||'Other'}
function derivedSetName(data:StoreData,item:Item){const c=itemCollection(data,item);if(c&&c.id!=='unlabeled-system'&&!/^unlabeled$/i.test(c.name))return c.name;const f=item.customFields||{};return f.Set||f.Series||f.Collection||item.identity?.series||item.identity?.brand||item.category||'Unsorted'}
function productNumber(item:Item){return item.customFields?.Number||item.customFields?.number||item.identity?.collectorNumber||item.identity?.sku||''}
function ownedQty(item:Item){return item.status==='owned'?item.quantity:0}
function holdingValue(item:Item){return item.status==='owned'?item.currentValue*item.quantity:0}
function itemChange(item:Item){const pts=(item.priceHistory||[]).filter(p=>p.kind!=='sale').slice(-2);if(pts.length<2)return{delta:0,pct:0};const a=pts[0].value,b=pts[1].value,delta=b-a;return{delta,pct:a?delta/a*100:0}}
function fmtChange(delta:number,pct:number){const s=delta>=0?'+':'';return `${s}${money(delta)} (${s}${pct.toFixed(2)}%)`}
function isWishlisted(item:Item){return item.status==='wishlist'||item.customFields?.__wishlist==='true'}
function fileDataUrl(file:File){return new Promise<string>((resolve,reject)=>{const r=new FileReader();r.onload=()=>resolve(String(r.result||''));r.onerror=()=>reject(r.error);r.readAsDataURL(file)})}
function rangeMs(range:RangeKey){return range==='1D'?864e5:range==='7D'?6048e5:range==='1M'?2592e6:range==='3M'?7776e6:range==='6M'?15552e6:Infinity}
function totalSnapshot(values:Record<string,number>){return Object.values(values||{}).reduce((a,b)=>a+(Number(b)||0),0)}
function chartPoints(data:StoreData,current:number,range:RangeKey){const cutoff=Date.now()-rangeMs(range);let pts=(data.history||[]).map(h=>({date:h.date,value:totalSnapshot(h.values)})).filter(p=>range==='MAX'||Date.parse(p.date)>=cutoff);const now={date:nowIso(),value:current};if(!pts.length)pts=[{date:new Date(Date.now()-864e5).toISOString(),value:current},now];else if(pts.at(-1)!.date.slice(0,10)===now.date.slice(0,10))pts[pts.length-1]=now;else pts.push(now);if(pts.length===1)pts.unshift({date:new Date(Date.parse(pts[0].date)-864e5).toISOString(),value:pts[0].value});return pts}
function currentMonth(){const d=new Date();return `${d.getFullYear()}-${String(d.getMonth()+1).padStart(2,'0')}`}
function defaultPrefs(data:StoreData){return data.preferences||{accentColor:'#ff1f2d',density:'comfortable' as const,cardSize:'standard' as const,reducedMotion:false}}

export default function DesktopCollector({status,profileName,data,update,config,session}:Props){
  const [view,setView]=useState<View>('home'),[searchScreen,setSearchScreen]=useState<SearchScreen>('filters'),[selectedCategory,setSelectedCategory]=useState(''),[selectedSet,setSelectedSet]=useState<SetGroup|null>(null),[detailId,setDetailId]=useState<string|null>(null),[query,setQuery]=useState(''),[editMode,setEditMode]=useState(false),[editTarget,setEditTarget]=useState<EditTarget|null>(null),[createKind,setCreateKind]=useState<'filter'|'set'|null>(null),[picker,setPicker]=useState(false),[progress,setProgress]=useState(false),[collectionsOpen,setCollectionsOpen]=useState(false),[layoutOpen,setLayoutOpen]=useState(false),[toast,setToast]=useState('');
  const notify=(s:string)=>{setToast(s);window.setTimeout(()=>setToast(''),2200)};
  const owned=useMemo(()=>data.items.filter(i=>i.status==='owned'),[data.items]),portfolioValue=useMemo(()=>owned.reduce((n,i)=>n+holdingValue(i),0),[owned]);
  const categories=useMemo<CategoryGroup[]>(()=>{const map=new Map<string,Item[]>();for(const item of data.items){const n=itemCategory(data,item);map.set(n,[...(map.get(n)||[]),item])}const groups=[...map.entries()].map(([rawName,items])=>{const key=categoryKey(rawName);return{key,rawName,name:groupName(data,key,rawName),items,cover:groupCover(data,key)}});for(const [key,meta] of Object.entries(data.libraryGroups||{})){if(!key.startsWith('mobile-category::')||!meta.name||groups.some(g=>g.key===key))continue;groups.push({key,rawName:key,name:meta.name,items:[],cover:meta.coverImage||''})}return groups.sort((a,b)=>a.name.localeCompare(b.name))},[data]);
  const sets=useMemo<SetGroup[]>(()=>{if(!selectedCategory)return[];const category=categories.find(c=>c.rawName===selectedCategory);const map=new Map<string,SetGroup>();for(const item of category?.items||[]){const c=itemCollection(data,item);if(c&&c.id!=='unlabeled-system'&&!/^unlabeled$/i.test(c.name)){const key=`collection::${c.id}`,e=map.get(key);if(e)e.items.push(item);else map.set(key,{key,rawName:c.name,name:c.name,items:[item],cover:c.coverImage||'',collectionId:c.id})}else{const raw=derivedSetName(data,item),key=setKey(selectedCategory,raw),e=map.get(key);if(e)e.items.push(item);else map.set(key,{key,rawName:raw,name:groupName(data,key,raw),items:[item],cover:groupCover(data,key)})}}for(const c of data.collections){if(c.id!=='unlabeled-system'&&c.libraryLine===selectedCategory&&!map.has(`collection::${c.id}`))map.set(`collection::${c.id}`,{key:`collection::${c.id}`,rawName:c.name,name:c.name,items:[],cover:c.coverImage||'',collectionId:c.id})}return [...map.values()].sort((a,b)=>a.name.localeCompare(b.name))},[data,categories,selectedCategory]);
  const activeSet=selectedSet?(sets.find(s=>s.key===selectedSet.key)||selectedSet):null;
  const detail=data.items.find(i=>i.id===detailId)||null;
  const patch=(fn:(d:StoreData)=>StoreData)=>update(fn(data));
  const addOne=(id:string)=>patch(d=>({...d,items:d.items.map(i=>i.id===id?{...i,status:'owned',quantity:i.status==='owned'?i.quantity+1:1,customFields:Object.fromEntries(Object.entries(i.customFields||{}).filter(([k])=>k!=='__wishlist')),updatedAt:nowIso()}:i)}));
  const moveWishlist=(id:string)=>patch(d=>({...d,items:d.items.map(i=>i.id===id?{...i,status:'wishlist',quantity:Math.max(1,i.quantity),customFields:Object.fromEntries(Object.entries(i.customFields||{}).filter(([k])=>k!=='__wishlist')),updatedAt:nowIso()}:i)}));
  const setQty=(id:string,n:number)=>patch(d=>({...d,items:d.items.map(i=>i.id===id?{...i,status:n>0?'owned':'wishlist',quantity:Math.max(1,Math.floor(n)),updatedAt:nowIso()}:i)}));
  const createProduct=()=>{const id=crypto.randomUUID(),collectionId=data.collections.find(c=>c.id!=='unlabeled-system')?.id||'';const item:Item={id,collectionId,name:'New Product',category:'Other',status:'owned',purchasePrice:0,currentValue:0,quantity:1,image:'',condition:'',purchaseDate:new Date().toISOString().slice(0,10),location:'',notes:'',customFields:{},identity:{marketCategory:'other'},createdAt:nowIso(),updatedAt:nowIso()};update({...data,items:[...data.items,item]});window.setTimeout(()=>setEditTarget({kind:'product',itemId:id}),0)};
  const nav=(next:View)=>{setView(next);setEditMode(false);setDetailId(null);if(next!=='search')setSearchScreen('filters')};
  return <div className="dc-shell"><DesktopCommunitySync config={config} session={session} data={data} fallbackName={profileName}/><DesktopHeader view={view} nav={nav} status={status}/><main className="dc-main">{view==='home'&&<DesktopHome data={data} update={update} owned={owned} value={portfolioValue} goPerformance={()=>nav('home')}/>} {view==='portfolio'&&<DesktopPortfolio data={data} update={update} items={owned} value={portfolioValue} openProduct={setDetailId} addOne={addOne} notify={notify} editProduct={(id)=>setEditTarget({kind:'product',itemId:id})} createProduct={createProduct} manageCollections={()=>setCollectionsOpen(true)} layoutSettings={()=>setLayoutOpen(true)}/>} {view==='search'&&<DesktopSearch data={data} update={update} categories={categories} sets={sets} screen={searchScreen} setScreen={setSearchScreen} selectedCategory={selectedCategory} setSelectedCategory={setSelectedCategory} selectedSet={activeSet} setSelectedSet={setSelectedSet} openProduct={setDetailId} addOne={addOne} query={query} setQuery={setQuery} editMode={editMode} setEditMode={setEditMode} edit={(t)=>setEditTarget(t)} create={(k)=>setCreateKind(k)} picker={()=>setPicker(true)} progress={()=>setProgress(true)}/>} {view==='wishlist'&&<DesktopWishlist data={data} update={update} openProduct={setDetailId} notify={notify}/>} {view==='social'&&<DesktopSocial config={config} session={session} data={data} fallbackName={profileName} notify={notify}/>} {view==='profile'&&<DesktopProfile config={config} session={session} data={data} fallbackName={profileName} notify={notify} openProduct={setDetailId}/>}</main>{detail&&<ProductDetail item={detail} data={data} update={update} close={()=>setDetailId(null)} addOne={()=>addOne(detail.id)} setQty={(n)=>setQty(detail.id,n)} moveWishlist={()=>moveWishlist(detail.id)} edit={()=>setEditTarget({kind:'product',itemId:detail.id})} notify={notify}/>} {editTarget&&<EditModal data={data} target={editTarget} update={update} close={()=>setEditTarget(null)} notify={notify}/>} {createKind&&<CreateModal data={data} kind={createKind} selectedCategory={selectedCategory} update={update} close={()=>setCreateKind(null)} notify={notify}/>} {picker&&activeSet&&<PickerModal data={data} target={activeSet} category={selectedCategory} update={update} close={()=>setPicker(false)} notify={notify}/>} {progress&&activeSet&&<ProgressModal data={data} target={activeSet} update={update} close={()=>setProgress(false)} notify={notify}/>} {collectionsOpen&&<CollectionManagerModal data={data} update={update} close={()=>setCollectionsOpen(false)} notify={notify}/>} {layoutOpen&&<LayoutSettingsModal data={data} update={update} close={()=>setLayoutOpen(false)} notify={notify}/>} {toast&&<div className="dc-toast">{toast}</div>}</div>;
}

function DesktopHeader({view,nav,status}:{view:View;nav:(v:View)=>void;status:string}){const items:[View,string][]=[['home','Home'],['portfolio','Portfolio'],['search','Search'],['wishlist','Wishlist'],['social','Social'],['profile','Profile']];return <header className="dc-header"><div className="dc-header-inner"><button className="dc-brand" onClick={()=>nav('home')} aria-label="VEXUM home"><span className="dc-brand-mark">V</span><span className="dc-brand-word">VEXUM</span></button><nav>{items.map(([id,label])=><button key={id} className={view===id?'active':''} onClick={()=>nav(id)}>{label}</button>)}</nav><div className="dc-header-right"><button className="dc-command" onClick={()=>nav('search')}><Search/><span>Search your collection...</span><kbd>⌘ K</kbd></button><span className="dc-sync-dot">{status}</span><button className="dc-currency">USD</button></div></div></header>}

function DesktopHome({data,update,owned,value,goPerformance}:{data:StoreData;update:(s:StoreData)=>void;owned:Item[];value:number;goPerformance:()=>void}){
  const [tab,setTab]=useState<'overview'|'performance'>('overview'),[range,setRange]=useState<RangeKey>('1M');const most=[...owned].sort((a,b)=>holdingValue(b)-holdingValue(a)).slice(0,10);const cost=owned.reduce((n,i)=>n+i.purchasePrice*i.quantity,0),gain=value-cost,month=currentMonth(),spent=owned.filter(i=>i.purchaseDate?.slice(0,7)===month).reduce((n,i)=>n+i.purchasePrice*i.quantity,0);const prefs:any=defaultPrefs(data),budget=Number(prefs.monthlyCollectingBudget||0),remaining=budget-spent;const setBudget=(n:number)=>update({...data,preferences:{...defaultPrefs(data),monthlyCollectingBudget:String(Math.max(0,n))} as any});
  return <div className="dc-page"><div className="dc-home-tabs"><div className="dc-segment-tabs compact"><button className={tab==='overview'?'active':''} onClick={()=>setTab('overview')}>Overview</button><button className={tab==='performance'?'active':''} onClick={()=>setTab('performance')}>Performance</button></div><button className="dc-dollar-button" onClick={()=>setTab('performance')} title="Performance & budget"><CircleDollarSign/></button></div>{tab==='overview'?<div className="dc-home-grid"><section className="dc-card dc-chart-card"><div className="dc-chart-head"><div><span>Portfolio: <b>Collecting</b></span><strong>{money(value)}</strong><small className={gain>=0?'gain':'loss'}>{gain>=0?'+':''}{money(gain)} vs. cost basis</small></div><div className="dc-chart-metric"><span>Owned products</span><b>{owned.length}</b></div></div><PortfolioChart data={data} value={value} range={range}/><RangeRow range={range} setRange={setRange}/></section><aside className="dc-card dc-most"><h2>Most Valuable</h2><p>Your ten highest-value holdings.</p><div>{most.map(i=><div key={i.id}><span>{i.name}<small>{i.condition||'Unspecified'}</small></span><b>{money(holdingValue(i))}</b></div>)}</div></aside></div>:<div className="dc-performance-grid"><section className="dc-card"><div className="dc-section-head"><div><h2>Monthly collecting budget</h2><p>Manual collection purchases are counted now. Bank transaction matching can be connected with Plaid later.</p></div><button className="dc-secondary" onClick={()=>alert('Plaid integration is the next connection layer. The budget and transaction-classification UI is ready for it.')}><CircleDollarSign/>Connect Bank</button></div><div className="dc-budget-grid"><label>Monthly budget<input type="number" min="0" step="1" value={budget||''} placeholder="0" onChange={e=>setBudget(Number(e.target.value))}/></label><div><span>Spent this month</span><b>{money(spent)}</b></div><div><span>{remaining>=0?'Remaining':'Over budget'}</span><b className={remaining>=0?'gain':'loss'}>{money(Math.abs(remaining))}</b></div></div><div className="dc-budget-bar"><i style={{width:`${budget?Math.min(100,spent/budget*100):0}%`}}/></div></section><section className="dc-card dc-chart-card"><div className="dc-chart-head"><div><span>Collection market gain</span><strong className={gain>=0?'gain':'loss'}>{gain>=0?'+':''}{money(gain)}</strong><small>{cost?`${gain>=0?'+':''}${(gain/cost*100).toFixed(2)}% vs. ${money(cost)} paid`:'Add purchase prices to calculate gain/loss.'}</small></div></div><PortfolioChart data={data} value={value} range={range}/><RangeRow range={range} setRange={setRange}/></section></div>}</div>;
}
function PortfolioChart({data,value,range}:{data:StoreData;value:number;range:RangeKey}){const id=useId().replace(/:/g,''),pts=chartPoints(data,value,range),w=1000,h=300,p=10,min=Math.min(...pts.map(x=>x.value)),max=Math.max(...pts.map(x=>x.value)),span=Math.max(1,max-min),x=(i:number)=>i/(Math.max(1,pts.length-1))*w,y=(v:number)=>p+(1-(v-min)/span)*(h-p*2),line=pts.map((pt,i)=>`${i?'L':'M'}${x(i).toFixed(1)} ${y(pt.value).toFixed(1)}`).join(' '),area=`${line} L${w} ${h} L0 ${h} Z`;return <div className="dc-chart"><svg viewBox={`0 0 ${w} ${h}`} preserveAspectRatio="none"><defs><linearGradient id={id} x1="0" y1="0" x2="0" y2="1"><stop offset="0" stopColor="#ff1f2d" stopOpacity=".32"/><stop offset="1" stopColor="#ff1f2d" stopOpacity="0"/></linearGradient></defs><path d={area} fill={`url(#${id})`}/><path d={line} fill="none" stroke="#ff1f2d" strokeWidth="3" vectorEffect="non-scaling-stroke"/></svg></div>}
function RangeRow({range,setRange}:{range:RangeKey;setRange:(r:RangeKey)=>void}){return <div className="dc-ranges">{ranges.map(r=><button key={r} className={range===r?'active':''} onClick={()=>setRange(r)}>{r}</button>)}</div>}

function DesktopPortfolio({data,update,items,value,openProduct,addOne,notify,editProduct,createProduct,manageCollections,layoutSettings}:{data:StoreData;update:(s:StoreData)=>void;items:Item[];value:number;openProduct:(id:string)=>void;addOne:(id:string)=>void;notify:(s:string)=>void;editProduct:(id:string)=>void;createProduct:()=>void;manageCollections:()=>void;layoutSettings:()=>void}){
  const [q,setQ]=useState(''),[sort,setSort]=useState(sortOptions[1]),[selectMode,setSelectMode]=useState(false),[selected,setSelected]=useState<string[]>([]),[customize,setCustomize]=useState(false),input=useRef<HTMLInputElement|null>(null);
  const prefs:any=defaultPrefs(data),columns=Math.max(4,Math.min(8,Number(prefs.desktopColumns||6))),imageHeight=Math.max(170,Math.min(330,Number(prefs.desktopImageHeight||235))),showChanges=String(prefs.desktopShowChanges??'true')!=='false',showIdentifier=String(prefs.desktopShowIdentifier??'true')!=='false';
  let shown=items.filter(i=>!q||[i.name,i.category,i.identity?.brand,i.identity?.series,i.identity?.sku,i.identity?.upc,i.identity?.modelNumber,i.identity?.collectorNumber,data.collections.find(c=>c.id===i.collectionId)?.name].filter(Boolean).join(' ').toLowerCase().includes(q.toLowerCase()));
  shown=[...shown].sort((a,b)=>sort==='Price: Low to High'?a.currentValue-b.currentValue:sort==='Price: High to Low'?b.currentValue-a.currentValue:sort==='Name: A to Z'?a.name.localeCompare(b.name):sort==='Name: Z to A'?b.name.localeCompare(a.name):b.createdAt.localeCompare(a.createdAt));
  const importFile=async(file:File)=>{try{const parsed=JSON.parse(await file.text());if(!validStore(parsed))throw new Error('That JSON is not a valid Collector workspace.');update(parsed);notify('Collection imported')}catch(e){notify(e instanceof Error?e.message:'Import failed')}};
  const exportData=()=>{const blob=new Blob([JSON.stringify(data,null,2)],{type:'application/json'}),a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download=`collector-${new Date().toISOString().slice(0,10)}.json`;a.click();URL.revokeObjectURL(a.href)};
  const share=async()=>{const text=`My Collector portfolio is ${money(value)} across ${items.length} products.`;if(navigator.share)await navigator.share({title:'My Collector Portfolio',text,url:location.href}).catch(()=>{});else{await navigator.clipboard?.writeText(`${text} ${location.href}`);notify('Share link copied')}};
  return <div className="dc-page dc-portfolio-page"><div className="dc-portfolio-center"><div className="dc-page-head"><div><h1>Portfolio</h1><p>Portfolio: <b>Collecting</b> · {money(value)}</p></div><div className="dc-head-actions"><button className="dc-primary" onClick={createProduct}><Plus/>Add Product</button><button className="dc-secondary" onClick={manageCollections}><Layers3/>Collections</button><button className={`dc-secondary ${customize?'active':''}`} onClick={()=>{setCustomize(v=>!v);setSelectMode(false);setSelected([])}}><PenLine/>{customize?'Done Customizing':'Customize'}</button><button className="dc-secondary" onClick={layoutSettings}><SlidersHorizontal/>Layout</button></div></div><div className="dc-search-panel large"><Search/><input placeholder="Search your collection" value={q} onChange={e=>setQ(e.target.value)}/>{q&&<button onClick={()=>setQ('')}><X/></button>}</div><div className="dc-toolbar"><div className="dc-tool-group"><button onClick={()=>input.current?.click()}><FileUp/>Import</button><button className={selectMode?'active':''} onClick={()=>{setSelectMode(v=>!v);setCustomize(false);setSelected([])}}><Layers3/>Bulk Actions</button><button onClick={exportData}><Download/>Export</button><button onClick={share}><Share2/>Share</button><input hidden ref={input} type="file" accept="application/json,.json" onChange={e=>{const f=e.target.files?.[0];if(f)importFile(f);e.currentTarget.value=''}}/></div><select value={sort} onChange={e=>setSort(e.target.value)}>{sortOptions.map(s=><option key={s}>{s}</option>)}</select></div><div className="dc-product-grid dc-portfolio-grid" style={{gridTemplateColumns:`repeat(${columns},minmax(0,1fr))`,'--dc-product-image-height':`${imageHeight}px`} as any}>{shown.map(item=><ProductCard key={item.id} item={item} data={data} open={()=>openProduct(item.id)} add={()=>addOne(item.id)} selectMode={selectMode} selected={selected.includes(item.id)} toggle={()=>setSelected(selected.includes(item.id)?selected.filter(x=>x!==item.id):[...selected,item.id])} edit={customize?()=>editProduct(item.id):undefined} showChanges={showChanges} showIdentifier={showIdentifier}/>)}</div>{selectMode&&<div className="dc-selection-bar"><span>{selected.length} selected</span><button onClick={()=>setSelected([])}>Clear</button><button className="dc-primary" onClick={()=>setSelectMode(false)}>Done</button></div>}</div></div>;
}
function ProductCard({item,data,open,add,selectMode=false,selected=false,toggle,edit,showChanges=true,showIdentifier=true}:{item:Item;data:StoreData;open:()=>void;add:()=>void;selectMode?:boolean;selected?:boolean;toggle?:()=>void;edit?:()=>void;showChanges?:boolean;showIdentifier?:boolean}){const ch=itemChange(item);return <article className={`dc-product-card ${selected?'selected':''}`} onClick={selectMode?toggle:open}><div className="dc-product-media">{item.image?<img src={item.image} alt=""/>:<span/>}{selected&&<i>✓</i>}{edit&&<button className="dc-card-edit" onClick={e=>{e.stopPropagation();edit()}}><PenLine/></button>}</div><h3>{item.name}</h3><p>{data.collections.find(c=>c.id===item.collectionId)?.name||derivedSetName(data,item)}</p>{showIdentifier&&<small>{productNumber(item)||item.identity?.upc||item.identity?.modelNumber||''}</small>}<footer><div><b>{money(item.currentValue)}</b>{showChanges&&<em className={ch.delta>=0?'gain':'loss'}>{fmtChange(ch.delta,ch.pct)}</em>}<span>Qty: {ownedQty(item)}</span></div><button className="dc-add-one" onClick={e=>{e.stopPropagation();add()}}><Plus/></button></footer></article>}

function DesktopSearch({data,update,categories,sets,screen,setScreen,selectedCategory,setSelectedCategory,selectedSet,setSelectedSet,openProduct,addOne,query,setQuery,editMode,setEditMode,edit,create,picker,progress}:{data:StoreData;update:(s:StoreData)=>void;categories:CategoryGroup[];sets:SetGroup[];screen:SearchScreen;setScreen:(s:SearchScreen)=>void;selectedCategory:string;setSelectedCategory:(s:string)=>void;selectedSet:SetGroup|null;setSelectedSet:(s:SetGroup|null)=>void;openProduct:(id:string)=>void;addOne:(id:string)=>void;query:string;setQuery:(s:string)=>void;editMode:boolean;setEditMode:(v:boolean)=>void;edit:(t:EditTarget)=>void;create:(k:'filter'|'set')=>void;picker:()=>void;progress:()=>void}){
  if(screen==='filters')return <div className="dc-page"><div className="dc-page-head"><div><h1>Search</h1><p>Browse your collection using the same category → set → product flow.</p></div><button className={`dc-secondary ${editMode?'active':''}`} onClick={()=>setEditMode(!editMode)}><PenLine/>{editMode?'Done':'Edit'}</button></div><div className="dc-search-panel large"><Search/><input placeholder="Search filters" value={query} onChange={e=>setQuery(e.target.value)}/></div><div className="dc-section-title"><h2>Quick Filters</h2>{editMode&&<button className="dc-red-outline" onClick={()=>create('filter')}><Plus/>Add Filter</button>}</div><div className="dc-filter-cover-grid">{categories.filter(c=>!query||c.name.toLowerCase().includes(query.toLowerCase())).map(c=><button key={c.key} className="dc-filter-cover" title={c.name} style={c.cover?{backgroundImage:`url(${c.cover})`}:undefined} onClick={()=>{setSelectedCategory(c.rawName);setQuery('');setScreen('sets')}}>{!c.cover&&<span className="dc-cover-placeholder"/>}{editMode&&<i onClick={e=>{e.stopPropagation();edit({kind:'category',key:c.key,rawName:c.rawName,name:c.name})}}><PenLine/></i>}</button>)}</div></div>;
  if(screen==='sets')return <div className="dc-page"><div className="dc-page-head"><div><button className="dc-back-link" onClick={()=>setScreen('filters')}><ArrowLeft/>Quick Filters</button><h1>Sets</h1><p>{categories.find(c=>c.rawName===selectedCategory)?.name||selectedCategory}</p></div><div className="dc-head-actions"><button className={`dc-secondary ${editMode?'active':''}`} onClick={()=>setEditMode(!editMode)}><PenLine/>{editMode?'Done':'Edit'}</button>{editMode&&<button className="dc-red-outline" onClick={()=>create('set')}><Plus/>Add Set</button>}</div></div><div className="dc-search-panel"><Search/><input placeholder="Search sets" value={query} onChange={e=>setQuery(e.target.value)}/></div><div className="dc-set-grid">{sets.filter(s=>!query||s.name.toLowerCase().includes(query.toLowerCase())).map(s=>{const p=getProgress(data,s);return <button className="dc-set-card" key={s.key} style={s.cover?{backgroundImage:`linear-gradient(180deg,transparent 20%,rgba(0,0,0,.82)),url(${s.cover})`}:undefined} onClick={()=>{setSelectedSet(s);setQuery('');setScreen('set')}}><div><h3>{s.name}</h3>{p.enabled?<><small>{p.owned}/{p.target} · {p.percent}% complete</small><div className="dc-set-progress"><i style={{width:`${p.percent}%`}}/></div></>:<small>{s.items.reduce((n,i)=>n+ownedQty(i),0)} owned · {money(s.items.reduce((n,i)=>n+holdingValue(i),0))}</small>}</div>{editMode&&<i className="edit" onClick={e=>{e.stopPropagation();edit({kind:'set',key:s.key,rawName:s.rawName,name:s.name,collectionId:s.collectionId})}}><PenLine/></i>}</button>})}</div></div>;
  const group=selectedSet,items=(group?.items||[]).filter(i=>!query||i.name.toLowerCase().includes(query.toLowerCase())),p=group?getProgress(data,group):null;return <div className="dc-page"><div className="dc-page-head"><div><button className="dc-back-link" onClick={()=>setScreen('sets')}><ArrowLeft/>Sets</button><h1>{group?.name||'Set'}</h1><p>{p?.enabled?`${p.owned}/${p.target} collected · ${p.percent}% complete`:`${group?.items.reduce((n,i)=>n+ownedQty(i),0)||0} owned`}</p></div><div className="dc-head-actions"><button className="dc-secondary" onClick={progress}>Update Progress</button><button className={`dc-secondary ${editMode?'active':''}`} onClick={()=>setEditMode(!editMode)}><PenLine/>{editMode?'Done':'Edit'}</button>{editMode&&<button className="dc-red-outline" onClick={picker}><Plus/>Add to Collection</button>}</div></div>{p?.enabled&&<div className="dc-large-progress"><i style={{width:`${p.percent}%`}}/><span>{p.percent}%</span></div>}<div className="dc-search-panel"><Search/><input placeholder="Search products in this set" value={query} onChange={e=>setQuery(e.target.value)}/></div><div className="dc-product-grid wide">{items.map(item=><ProductCard key={item.id} item={item} data={data} open={()=>openProduct(item.id)} add={()=>addOne(item.id)} edit={editMode?()=>edit({kind:'product',itemId:item.id}):undefined}/>)}</div></div>;
}

function ProductDetail({item,data,update,close,addOne,setQty,moveWishlist,edit,notify}:{item:Item;data:StoreData;update:(s:StoreData)=>void;close:()=>void;addOne:()=>void;setQty:(n:number)=>void;moveWishlist:()=>void;edit:()=>void;notify:(s:string)=>void}){
  const [grade,setGrade]=useState<'RAW'|'GRADED'|'POP'>('RAW'),[busy,setBusy]=useState(false),[message,setMessage]=useState('');const qty=ownedQty(item),ch=itemChange(item),sold='https://www.ebay.com/sch/i.html?'+new URLSearchParams({_nkw:marketQuery(item),LH_Sold:'1',LH_Complete:'1'});
  const market=async()=>{setBusy(true);setMessage('');try{const r=await fetch('/api/market',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({item})}),j=await r.json();if(!r.ok)throw new Error(j.error||'Market lookup unavailable');const value=Number(j.value);if(!Number.isFinite(value)||value<=0)throw new Error('No usable value returned');const date=nowIso(),point={date,value,variant:variantKey(item),source:String(j.source||'Market'),url:String(j.url||''),kind:'provider' as const};update({...data,items:data.items.map(i=>i.id===item.id?{...i,currentValue:value,updatedAt:date,identity:{...(i.identity||{}),...(j.identifiers||{})},marketLink:{provider:String(j.source||'Market'),query:String(j.searchQuery||marketQuery(item)),linkedAt:i.marketLink?.linkedAt||date,lastRefresh:date},priceHistory:[...(i.priceHistory||[]),point].slice(-3000)}:i)});setMessage(`${j.source||'Market'} · ${money(value)}`);notify('Market value updated')}catch(e){setMessage(e instanceof Error?e.message:'Market lookup unavailable')}finally{setBusy(false)}};
  return <div className="dc-modal-backdrop detail" onMouseDown={close}><section className="dc-product-detail" onMouseDown={e=>e.stopPropagation()}><div className="dc-detail-hero">{item.image&&<div className="dc-detail-blur" style={{backgroundImage:`url(${item.image})`}}/>}<button className="dc-detail-back" onClick={close}><ArrowLeft/></button><div className="dc-detail-controls"><button className={isWishlisted(item)?'active':''} title="Move to wishlist" onClick={moveWishlist}><Star fill={isWishlisted(item)?'currentColor':'none'}/></button><button title="Edit product" onClick={edit}><PenLine/></button></div>{item.image?<img src={item.image} alt=""/>:<span/>}</div><div className="dc-detail-body"><div className="dc-detail-title"><div><h2>{item.name}</h2><p>{derivedSetName(data,item)}{productNumber(item)?` · ${productNumber(item)}`:''}</p></div><div><strong>{money(item.currentValue)}</strong><small className={ch.delta>=0?'gain':'loss'}>{fmtChange(ch.delta,ch.pct)}</small></div></div><div className="dc-detail-actions"><button className="dc-red-outline" onClick={()=>window.open(sold,'_blank','noopener,noreferrer')}><ShoppingBag/>View Sold Listings</button><div className="dc-qty"><button onClick={()=>setQty(qty-1)}><Minus/></button><span>{qty}</span><button onClick={()=>setQty(qty+1)}><Plus/></button></div></div><div className="dc-grade-tabs">{(['RAW','GRADED','POP'] as const).map(g=><button key={g} className={grade===g?'active':''} onClick={()=>setGrade(g)}>{g}</button>)}</div><div className="dc-detail-value-card"><span>Current market value</span><b>{money(item.currentValue)}</b><small>{grade==='RAW'?'Raw / current condition':grade==='GRADED'?'Graded reference':'Population reference'}</small></div><div className="dc-detail-buttons"><button className="dc-primary" disabled={busy} onClick={market}>{busy?'Checking…':'Check Market Value'}</button><button className="dc-secondary" onClick={addOne}><Plus/>Add 1 to Collection</button></div>{message&&<div className="dc-market-message">{message}</div>}</div></section></div>;
}

function Modal({title,close,children,wide=false}:{title:string;close:()=>void;children:React.ReactNode;wide?:boolean}){return <div className="dc-modal-backdrop" onMouseDown={close}><section className={`dc-modal ${wide?'wide':''}`} onMouseDown={e=>e.stopPropagation()}><header><h3>{title}</h3><button onClick={close}><X/></button></header><div className="dc-modal-scroll">{children}</div></section></div>}
function EditModal({data,target,update,close,notify}:{data:StoreData;target:EditTarget;update:(s:StoreData)=>void;close:()=>void;notify:(s:string)=>void}){
  const item=target.kind==='product'?data.items.find(i=>i.id===target.itemId):undefined;
  const set=target.kind==='set'&&target.collectionId?data.collections.find(c=>c.id===target.collectionId):undefined;
  const meta:any=target.kind!=='product'?groupMeta(data,target.key):{};
  const fallbackName=target.kind==='product'?(item?.name||'Product'):(set?.name||target.name);
  const [name,setName]=useState(fallbackName),[image,setImage]=useState(item?.image||set?.coverImage||meta.coverImage||''),[value,setValue]=useState(item?.currentValue||0),[paid,setPaid]=useState(item?.purchasePrice||0),[category,setCategory]=useState(item?.category||''),[collectionId,setCollectionId]=useState(item?.collectionId||''),[status,setStatus]=useState(item?.status||'owned'),[quantity,setQuantity]=useState(item?.quantity||1),[condition,setCondition]=useState(item?.condition||''),[purchaseDate,setPurchaseDate]=useState(item?.purchaseDate||''),[location,setLocation]=useState(item?.location||''),[notes,setNotes]=useState(item?.notes||''),[packaging,setPackaging]=useState(item?.packagingState||''),[identity,setIdentity]=useState<any>({...item?.identity}),[grading,setGrading]=useState<any>(item?.grading?{...item.grading}:{graded:false,company:'',grade:'',certification:'',designation:''}),[customPairs,setCustomPairs]=useState<[string,string][]>(Object.entries(item?.customFields||{}).filter(([k])=>!k.startsWith('__')) as [string,string][]),input=useRef<HTMLInputElement|null>(null);
  const setId=(key:string,value:string)=>setIdentity((x:any)=>({...x,[key]:value}));
  const save=()=>{
    if(target.kind==='product'){
      if(!item)return;
      const internal=Object.fromEntries(Object.entries(item.customFields||{}).filter(([k])=>k.startsWith('__'))),customFields={...internal,...Object.fromEntries(customPairs.map(([k,v])=>[k.trim(),v]).filter(([k])=>k))};
      update({...data,items:data.items.map(i=>i.id===item.id?{...i,name:name.trim()||i.name,image,currentValue:Math.max(0,Number(value)||0),purchasePrice:Math.max(0,Number(paid)||0),category:category.trim()||'Other',collectionId,status:status as Item['status'],quantity:Math.max(1,Math.floor(Number(quantity)||1)),condition,purchaseDate,location,notes,packagingState:(packaging||undefined) as Item['packagingState'],identity:Object.fromEntries(Object.entries(identity||{}).filter(([,v])=>String(v||'').trim()!=='')) as any,grading:grading.graded?{graded:true,company:String(grading.company||''),grade:String(grading.grade||''),certification:String(grading.certification||''),designation:String(grading.designation||'')}:{graded:false,company:'',grade:'',certification:'',designation:''},customFields,updatedAt:nowIso()}:i)});
    }else if(target.kind==='set'&&set){
      update({...data,collections:data.collections.map(c=>c.id===set.id?{...c,name:name.trim()||c.name,coverImage:image}:c)});
    }else{
      update({...data,libraryGroups:{...(data.libraryGroups||{}),[target.key]:{...groupMeta(data,target.key),name:name.trim()||target.name,coverImage:image}}});
    }
    notify('Saved');close();
  };
  const remove=()=>{if(!item||!window.confirm(`Delete ${item.name}? This removes it from Collector.`))return;update({...data,items:data.items.filter(i=>i.id!==item.id)});notify('Product removed');close()};
  return <Modal title={target.kind==='product'?'Edit Product':target.kind==='category'?'Edit Filter':'Edit Set'} close={close} wide={!!item}><div className="dc-form-grid dc-product-editor-grid"><label className="full">Name<input value={name} onChange={e=>setName(e.target.value)}/></label><label className="full">Cover / product image<div className="dc-upload-row"><button onClick={()=>input.current?.click()}><Upload/>Upload image</button>{image&&<img src={image} alt=""/>}</div></label>{item&&<>
    <div className="dc-editor-section full"><h4>Organization</h4><p>Control exactly where this product lives and how it is classified.</p></div>
    <label>Status<select value={status} onChange={e=>setStatus(e.target.value as Item['status'])}><option value="owned">Owned</option><option value="wishlist">Wishlist only</option><option value="sold">Sold archive</option></select></label>
    <label>Collection<select value={collectionId} onChange={e=>setCollectionId(e.target.value)}><option value="">Unassigned</option>{data.collections.filter(c=>c.id!=='unlabeled-system').map(c=><option key={c.id} value={c.id}>{c.name}</option>)}</select></label>
    <label>Category<input value={category} onChange={e=>setCategory(e.target.value)} placeholder="Action Figures, Comics, Trading Cards…"/></label>
    <label>Quantity<input type="number" min="1" step="1" value={quantity} onChange={e=>setQuantity(Math.max(1,Number(e.target.value)||1))}/></label>
    <label>Market value<input type="number" min="0" step="0.01" value={value} onChange={e=>setValue(Number(e.target.value))}/></label>
    <label>Price paid<input type="number" min="0" step="0.01" value={paid} onChange={e=>setPaid(Number(e.target.value))}/></label>
    <label>Purchase date<input type="date" value={purchaseDate} onChange={e=>setPurchaseDate(e.target.value)}/></label>
    <label>Location<input value={location} onChange={e=>setLocation(e.target.value)} placeholder="Shelf, display case, storage…"/></label>
    <label>Condition<input value={condition} onChange={e=>setCondition(e.target.value)} placeholder="Like New, NM, Used…"/></label>
    <label>Packaging<select value={packaging} onChange={e=>setPackaging(e.target.value)}><option value="">Not specified</option><option value="sealed">Sealed</option><option value="opened-box">Opened with box</option><option value="loose">Opened without box / loose</option></select></label>
    <div className="dc-editor-section full"><h4>Identity & market matching</h4><p>These identifiers make automatic market matching much more accurate.</p></div>
    <label>Brand<input value={identity.brand||''} onChange={e=>setId('brand',e.target.value)}/></label><label>Series / Line<input value={identity.series||''} onChange={e=>setId('series',e.target.value)}/></label>
    <label>UPC / GTIN<input value={identity.upc||''} onChange={e=>setId('upc',e.target.value)}/></label><label>SKU<input value={identity.sku||''} onChange={e=>setId('sku',e.target.value)}/></label>
    <label>Model #<input value={identity.modelNumber||''} onChange={e=>setId('modelNumber',e.target.value)}/></label><label>Collector #<input value={identity.collectorNumber||''} onChange={e=>setId('collectorNumber',e.target.value)}/></label>
    <label>Set code<input value={identity.setCode||''} onChange={e=>setId('setCode',e.target.value)}/></label><label>Edition / Variant<input value={identity.edition||''} onChange={e=>setId('edition',e.target.value)}/></label>
    <label>Year<input value={identity.year||''} onChange={e=>setId('year',e.target.value)}/></label><label>Language<input value={identity.language||''} onChange={e=>setId('language',e.target.value)}/></label>
    <label>Market category<select value={identity.marketCategory||'other'} onChange={e=>setId('marketCategory',e.target.value)}><option value="other">General collectible</option><option value="cards">Trading cards</option><option value="comics">Comics</option><option value="games">Games</option></select></label><label>PriceCharting ID<input value={identity.pricechartingId||''} onChange={e=>setId('pricechartingId',e.target.value)}/></label>
    <label>Scryfall ID<input value={identity.scryfallId||''} onChange={e=>setId('scryfallId',e.target.value)}/></label><label>TCGplayer ID<input value={identity.tcgplayerId||''} onChange={e=>setId('tcgplayerId',e.target.value)}/></label>
    <label>JustTCG ID<input value={identity.justtcgId||''} onChange={e=>setId('justtcgId',e.target.value)}/></label><label>JustTCG Variant ID<input value={identity.justtcgVariantId||''} onChange={e=>setId('justtcgVariantId',e.target.value)}/></label>
    <label>hobbyDB ID<input value={identity.hobbydbId||''} onChange={e=>setId('hobbydbId',e.target.value)}/></label><label>eBay EPID<input value={identity.ebayEpid||''} onChange={e=>setId('ebayEpid',e.target.value)}/></label>
    <label className="full">Description<textarea value={identity.description||''} onChange={e=>setId('description',e.target.value)} placeholder="Variant details, distinguishing features, release information…"/></label>
    <div className="dc-editor-section full"><h4>Grading</h4><p>Optional grading data for cards, comics, games, or other slabbed collectibles.</p></div>
    <label className="dc-check-label full"><input type="checkbox" checked={!!grading.graded} onChange={e=>setGrading((g:any)=>({...g,graded:e.target.checked}))}/> This item is graded</label>
    {grading.graded&&<><label>Grading company<input value={grading.company||''} onChange={e=>setGrading((g:any)=>({...g,company:e.target.value}))}/></label><label>Grade<input value={grading.grade||''} onChange={e=>setGrading((g:any)=>({...g,grade:e.target.value}))}/></label><label>Certification #<input value={grading.certification||''} onChange={e=>setGrading((g:any)=>({...g,certification:e.target.value}))}/></label><label>Designation<input value={grading.designation||''} onChange={e=>setGrading((g:any)=>({...g,designation:e.target.value}))} placeholder="Pristine, Black Label…"/></label></>}
    <div className="dc-editor-section full"><h4>Custom fields</h4><p>Create any additional metadata you want. These fields stay attached to this product.</p></div>
    <div className="dc-custom-fields full">{customPairs.map(([k,v],idx)=><div key={idx}><input placeholder="Field name" value={k} onChange={e=>setCustomPairs(customPairs.map((x,i)=>i===idx?[e.target.value,x[1]]:x) as [string,string][])}/><input placeholder="Value" value={v} onChange={e=>setCustomPairs(customPairs.map((x,i)=>i===idx?[x[0],e.target.value]:x) as [string,string][])}/><button onClick={()=>setCustomPairs(customPairs.filter((_,i)=>i!==idx))}><X/></button></div>)}<button className="dc-secondary" onClick={()=>setCustomPairs([...customPairs,['','']])}><Plus/>Add Custom Field</button></div>
    <label className="full">Notes<textarea value={notes} onChange={e=>setNotes(e.target.value)} placeholder="Private notes about this item…"/></label>
  </>}<input hidden ref={input} type="file" accept="image/*" onChange={async e=>{const f=e.target.files?.[0];if(f)setImage(await fileDataUrl(f));e.currentTarget.value=''}}/></div><div className="dc-modal-actions dc-editor-actions">{item?<button className="dc-danger" onClick={remove}>Delete Product</button>:<span/>}<div><button className="dc-secondary" onClick={close}>Cancel</button><button className="dc-primary" onClick={save}>Save</button></div></div></Modal>;
}

function CollectionManagerModal({data,update,close,notify}:{data:StoreData;update:(s:StoreData)=>void;close:()=>void;notify:(s:string)=>void}){
  const visible=data.collections.filter(c=>c.id!=='unlabeled-system'),[selectedId,setSelectedId]=useState(visible[0]?.id||''),selected=visible.find(c=>c.id===selectedId)||null,[draft,setDraft]=useState<any>(selected?{...selected}:{name:'',icon:'',color:'#ff1f2d',libraryType:'',libraryLine:'',coverImage:'',logo:''}),coverInput=useRef<HTMLInputElement|null>(null),logoInput=useRef<HTMLInputElement|null>(null);
  const choose=(id:string)=>{setSelectedId(id);const c=data.collections.find(x=>x.id===id);if(c)setDraft({...c})};
  const add=()=>{const id=crypto.randomUUID(),c:Collection={id,name:'New Collection',icon:'',color:'#ff1f2d',libraryType:'',libraryLine:'',coverImage:'',logo:''};update({...data,collections:[...data.collections,c]});setSelectedId(id);setDraft({...c});notify('Collection created')};
  const save=()=>{if(!selectedId)return;update({...data,collections:data.collections.map(c=>c.id===selectedId?{...c,...draft,name:String(draft.name||c.name).trim()||c.name,color:String(draft.color||'#ff1f2d')}:c)});notify('Collection updated')};
  const remove=()=>{const c=data.collections.find(x=>x.id===selectedId);if(!c||!window.confirm(`Delete ${c.name}? Products will become unassigned, not deleted.`))return;update({...data,collections:data.collections.filter(x=>x.id!==selectedId),items:data.items.map(i=>i.collectionId===selectedId?{...i,collectionId:'',updatedAt:nowIso()}:i)});const next=data.collections.find(x=>x.id!==selectedId&&x.id!=='unlabeled-system');setSelectedId(next?.id||'');setDraft(next?{...next}:{name:'',icon:'',color:'#ff1f2d',libraryType:'',libraryLine:'',coverImage:'',logo:''});notify('Collection removed')};
  return <Modal title="Manage Collections" close={close} wide><div className="dc-collection-manager"><aside><button className="dc-primary" onClick={add}><Plus/>New Collection</button><div>{visible.map(c=><button key={c.id} className={selectedId===c.id?'active':''} onClick={()=>choose(c.id)}><span>{c.coverImage?<img src={c.coverImage} alt=""/>:<i/>}</span><b>{c.name}</b><small>{data.items.filter(i=>i.collectionId===c.id).length} products</small></button>)}</div></aside><section>{selectedId?<><div className="dc-form-grid"><label className="full">Collection name<input value={draft.name||''} onChange={e=>setDraft({...draft,name:e.target.value})}/></label><label>Library type<input value={draft.libraryType||''} onChange={e=>setDraft({...draft,libraryType:e.target.value})} placeholder="Trading Cards, Action Figures…"/></label><label>Filter / category<input value={draft.libraryLine||''} onChange={e=>setDraft({...draft,libraryLine:e.target.value})} placeholder="Marvel Legends, Pokémon…"/></label><label>Icon name<input value={draft.icon||''} onChange={e=>setDraft({...draft,icon:e.target.value})}/></label><label>Accent color<input type="color" value={draft.color||'#ff1f2d'} onChange={e=>setDraft({...draft,color:e.target.value})}/></label><label className="full">Collection cover<div className="dc-upload-row"><button onClick={()=>coverInput.current?.click()}><Upload/>Upload Cover</button>{draft.coverImage&&<img src={draft.coverImage} alt=""/>}</div></label><label className="full">Collection logo / secondary image<div className="dc-upload-row"><button onClick={()=>logoInput.current?.click()}><Upload/>Upload Logo</button>{draft.logo&&<img src={draft.logo} alt=""/>}</div></label><input hidden ref={coverInput} type="file" accept="image/*" onChange={async e=>{const f=e.target.files?.[0];if(f)setDraft({...draft,coverImage:await fileDataUrl(f)});e.currentTarget.value=''}}/><input hidden ref={logoInput} type="file" accept="image/*" onChange={async e=>{const f=e.target.files?.[0];if(f)setDraft({...draft,logo:await fileDataUrl(f)});e.currentTarget.value=''}}/></div><div className="dc-collection-stats"><span><b>{data.items.filter(i=>i.collectionId===selectedId).length}</b> Products</span><span><b>{money(data.items.filter(i=>i.collectionId===selectedId&&i.status==='owned').reduce((n,i)=>n+holdingValue(i),0))}</b> Current value</span></div><div className="dc-modal-actions dc-editor-actions"><button className="dc-danger" onClick={remove}>Delete Collection</button><div><button className="dc-secondary" onClick={close}>Close</button><button className="dc-primary" onClick={save}>Save Collection</button></div></div></>:<div className="dc-empty"><b>Create your first collection</b><span>Collections can have their own covers, type, filter, icon, color, and products.</span></div>}</section></div></Modal>;
}

function LayoutSettingsModal({data,update,close,notify}:{data:StoreData;update:(s:StoreData)=>void;close:()=>void;notify:(s:string)=>void}){
  const prefs:any=defaultPrefs(data),[columns,setColumns]=useState(Math.max(4,Math.min(8,Number(prefs.desktopColumns||6)))),[imageHeight,setImageHeight]=useState(Math.max(170,Math.min(330,Number(prefs.desktopImageHeight||235)))),[showChanges,setShowChanges]=useState(String(prefs.desktopShowChanges??'true')!=='false'),[showIdentifier,setShowIdentifier]=useState(String(prefs.desktopShowIdentifier??'true')!=='false');
  const save=()=>{update({...data,preferences:{...defaultPrefs(data),desktopColumns:String(columns),desktopImageHeight:String(imageHeight),desktopShowChanges:String(showChanges),desktopShowIdentifier:String(showIdentifier)} as any});notify('Desktop layout saved');close()};
  return <Modal title="Portfolio Layout" close={close}><div className="dc-layout-settings"><label>Products per row <span>{columns}</span><input type="range" min="4" max="8" step="1" value={columns} onChange={e=>setColumns(Number(e.target.value))}/></label><label>Product image height <span>{imageHeight}px</span><input type="range" min="170" max="330" step="5" value={imageHeight} onChange={e=>setImageHeight(Number(e.target.value))}/></label><button className="dc-toggle-row" onClick={()=>setShowChanges(v=>!v)}><span>Show market change on cards</span><i className={showChanges?'on':''}/></button><button className="dc-toggle-row" onClick={()=>setShowIdentifier(v=>!v)}><span>Show SKU / collector number on cards</span><i className={showIdentifier?'on':''}/></button></div><div className="dc-modal-actions"><button className="dc-secondary" onClick={close}>Cancel</button><button className="dc-primary" onClick={save}>Save Layout</button></div></Modal>;
}

function CreateModal({data,kind,selectedCategory,update,close,notify}:{data:StoreData;kind:'filter'|'set';selectedCategory:string;update:(s:StoreData)=>void;close:()=>void;notify:(s:string)=>void}){const [name,setName]=useState(''),[cover,setCover]=useState(''),input=useRef<HTMLInputElement|null>(null);const save=()=>{if(!name.trim())return;if(kind==='filter'){const key=categoryKey(name+'-'+Date.now());update({...data,libraryGroups:{...(data.libraryGroups||{}),[key]:{name:name.trim(),coverImage:cover}}})}else{const c:Collection={id:crypto.randomUUID(),name:name.trim(),icon:'',color:'#ff1f2d',coverImage:cover,libraryLine:selectedCategory};update({...data,collections:[...data.collections,c]})}notify(kind==='filter'?'Filter added':'Set added');close()};return <Modal title={kind==='filter'?'Add Filter':'Add Set'} close={close}><div className="dc-form-grid"><label className="full">Name<input value={name} onChange={e=>setName(e.target.value)} autoFocus/></label><label className="full">Cover image<button className="dc-upload-button" onClick={()=>input.current?.click()}><Upload/>Upload cover</button>{cover&&<img className="dc-cover-preview" src={cover} alt=""/>}</label><input hidden ref={input} type="file" accept="image/*" onChange={async e=>{const f=e.target.files?.[0];if(f)setCover(await fileDataUrl(f));e.currentTarget.value=''}}/></div><div className="dc-modal-actions"><button className="dc-secondary" onClick={close}>Cancel</button><button className="dc-primary" onClick={save}>Create</button></div></Modal>}
function PickerModal({data,target,category,update,close,notify}:{data:StoreData;target:SetGroup;category:string;update:(s:StoreData)=>void;close:()=>void;notify:(s:string)=>void}){const [q,setQ]=useState(''),[selected,setSelected]=useState<string[]>([]);const candidates=data.items.filter(i=>!q||i.name.toLowerCase().includes(q.toLowerCase())).slice(0,500);const commit=()=>{let collectionId=target.collectionId,collections=data.collections;if(!collectionId){collectionId=crypto.randomUUID();collections=[...collections,{id:collectionId,name:target.name,icon:'',color:'#ff1f2d',coverImage:target.cover,libraryLine:category}]}update({...data,collections,items:data.items.map(i=>selected.includes(i.id)?{...i,collectionId:collectionId!,updatedAt:nowIso()}:i)});notify(`${selected.length} item${selected.length===1?'':'s'} added`);close()};return <Modal title={`Add to ${target.name}`} close={close} wide><div className="dc-search-panel"><Search/><input value={q} onChange={e=>setQ(e.target.value)} placeholder="Search your collection"/></div><div className="dc-picker-grid">{candidates.map(i=><button key={i.id} className={selected.includes(i.id)?'selected':''} onClick={()=>setSelected(selected.includes(i.id)?selected.filter(x=>x!==i.id):[...selected,i.id])}>{i.image?<img src={i.image} alt=""/>:<span/>}<b>{i.name}</b>{selected.includes(i.id)&&<i><Check/></i>}</button>)}</div><div className="dc-modal-actions"><button className="dc-secondary" onClick={close}>Cancel</button><button className="dc-primary" onClick={commit}>Add {selected.length||''}</button></div></Modal>}
function getProgress(data:StoreData,target:SetGroup){const meta:any=target.collectionId?data.collections.find(c=>c.id===target.collectionId):groupMeta(data,target.key);const enabled=String((meta as any)?.progressEnabled||'false')==='true',targetCount=Math.max(0,Number((meta as any)?.progressTarget||0)),owned=new Set(target.items.filter(i=>i.status==='owned').map(i=>i.id)).size,percent=targetCount?Math.min(100,Math.round(owned/targetCount*100)):0;return{enabled,target:targetCount,owned,percent}}
function ProgressModal({data,target,update,close,notify}:{data:StoreData;target:SetGroup;update:(s:StoreData)=>void;close:()=>void;notify:(s:string)=>void}){const p=getProgress(data,target),[enabled,setEnabled]=useState(p.enabled),[count,setCount]=useState(p.target||Math.max(1,target.items.length));const save=()=>{if(target.collectionId){update({...data,collections:data.collections.map(c=>c.id===target.collectionId?{...c,progressEnabled:String(enabled),progressTarget:String(Math.max(1,count))} as any:c)})}else update({...data,libraryGroups:{...(data.libraryGroups||{}),[target.key]:{...groupMeta(data,target.key),progressEnabled:String(enabled),progressTarget:String(Math.max(1,count))} as any}});notify('Progress settings updated');close()};return <Modal title="Set Progress" close={close}><div className="dc-progress-settings"><button className="dc-toggle-row" onClick={()=>setEnabled(v=>!v)}><span>Track set progression</span><i className={enabled?'on':''}/></button><label>Total items needed to finish<input type="number" min="1" value={count} onChange={e=>setCount(Math.max(1,Number(e.target.value)||1))}/></label><div className="dc-large-progress"><i style={{width:`${count?Math.min(100,Math.round(p.owned/count*100)):0}%`}}/><span>{count?Math.min(100,Math.round(p.owned/count*100)):0}%</span></div></div><div className="dc-modal-actions"><button className="dc-secondary" onClick={close}>Cancel</button><button className="dc-primary" onClick={save}>Save</button></div></Modal>}
