import {Store,validStore} from './model';
export type CloudConfig={url:string;key:string;configured:boolean};
export type Session={access_token:string;refresh_token:string;expires_at:number;user:{id:string;email?:string};recovery?:boolean};
const SESSION='collector.auth.session';
let current:Session|null=null;
let refreshing:Promise<Session>|null=null;
export class CloudConflict extends Error{constructor(){super('Another device changed your collection. Your edits are kept here. Download a backup, then load the latest cloud version.')}}
async function request(config:CloudConfig,path:string,options:RequestInit={},token?:string){const r=await fetch(config.url+path,{...options,headers:{apikey:config.key,'Content-Type':'application/json',...(token?{Authorization:'Bearer '+token}:{}),...options.headers},cache:'no-store',signal:AbortSignal.timeout(20000)});if(!r.ok){if(r.status===409)throw new CloudConflict();const error=await r.json().catch(()=>({}));if(r.status===401)throw new Error('Your sign-in expired. Sign in again; your local edits are preserved.');throw new Error(error.msg||error.message||error.error_description||'Cloud request failed. Check your connection and project setup.')}return r.status===204?null:r.json()}
function keep(session:Session|null){current=session;if(session)localStorage.setItem(SESSION,JSON.stringify(session));else localStorage.removeItem(SESSION)}
export async function cloudConfig():Promise<CloudConfig>{const r=await fetch('/api/cloud/config',{cache:'no-store'});if(!r.ok)throw new Error('Unable to load cloud configuration.');return r.json()}
export async function restoreSession(config:CloudConfig):Promise<Session|null>{const hash=new URLSearchParams(location.hash.slice(1));if(hash.has('error_description')){history.replaceState(null,'',location.pathname+location.search);throw new Error(hash.get('error_description')||'Sign-in failed.')}
if(hash.has('access_token')){const access=hash.get('access_token')!,refresh=hash.get('refresh_token')||'';const recovery=hash.get('type')==='recovery';history.replaceState(null,'',location.pathname+location.search);const user=await request(config,'/auth/v1/user',{},access);keep({access_token:access,refresh_token:refresh,expires_at:Date.now()/1000+Number(hash.get('expires_in')||3600),user,recovery})}else {const saved=localStorage.getItem(SESSION);if(saved){try{const parsed=JSON.parse(saved);if(typeof parsed.access_token==='string'&&typeof parsed.refresh_token==='string'&&typeof parsed.expires_at==='number'&&typeof parsed.user?.id==='string')current=parsed;else localStorage.removeItem(SESSION)}catch{localStorage.removeItem(SESSION)}}}
if(!current)return null;return freshSession(config)}
export async function freshSession(config:CloudConfig):Promise<Session>{if(!current)throw new Error('Sign in to sync your collection.');if(current.expires_at>Date.now()/1000+60)return current;if(!refreshing)refreshing=request(config,'/auth/v1/token?grant_type=refresh_token',{method:'POST',body:JSON.stringify({refresh_token:current.refresh_token})}).then(value=>{const session={...value,expires_at:Date.now()/1000+value.expires_in};keep(session);return session}).finally(()=>{refreshing=null});return refreshing}
function sessionFromAuth(value:any):Session|null{if(!value?.access_token||!value?.user?.id)return null;const session:Session={access_token:value.access_token,refresh_token:value.refresh_token||'',expires_at:Date.now()/1000+Number(value.expires_in||3600),user:value.user};keep(session);return session}
export async function signInPassword(config:CloudConfig,email:string,password:string){const value=await request(config,'/auth/v1/token?grant_type=password',{method:'POST',body:JSON.stringify({email,password})});const session=sessionFromAuth(value);if(!session)throw new Error('Unable to sign in. Check your email and password.');return session}
export async function signUpPassword(config:CloudConfig,email:string,password:string){const value=await request(config,'/auth/v1/signup?'+new URLSearchParams({redirect_to:location.origin+'/'}),{method:'POST',body:JSON.stringify({email,password})});return {session:sessionFromAuth(value),user:value?.user||null}}
export async function sendLogin(config:CloudConfig,email:string){return request(config,'/auth/v1/otp?'+new URLSearchParams({redirect_to:location.origin+'/'}),{method:'POST',body:JSON.stringify({email,create_user:true})})}

export async function sendPasswordReset(config:CloudConfig,email:string){const redirect=location.origin+'/';return request(config,'/auth/v1/recover?'+new URLSearchParams({redirect_to:redirect}),{method:'POST',body:JSON.stringify({email})})}
export async function updatePassword(config:CloudConfig,password:string){const session=await freshSession(config);const user=await request(config,'/auth/v1/user',{method:'PUT',body:JSON.stringify({password})},session.access_token);const updated={...session,user,recovery:false};keep(updated);return updated}
export async function logout(config:CloudConfig){try{const session=await freshSession(config);await request(config,'/auth/v1/logout?scope=local',{method:'POST'},session.access_token)}finally{keep(null)}}
export type CloudWorkspace={payload:Store;revision:number;updated_at:string};
export async function loadWorkspace(config:CloudConfig):Promise<CloudWorkspace|null>{const session=await freshSession(config);const rows=await request(config,'/rest/v1/collector_workspaces?'+new URLSearchParams({user_id:'eq.'+session.user.id,select:'payload,revision,updated_at'}),{},session.access_token);if(!rows.length)return null;if(!validStore(rows[0].payload))throw new Error('Cloud collection data is invalid. Export your local backup before continuing.');return rows[0]}
export async function saveWorkspace(config:CloudConfig,data:Store,revision:number):Promise<CloudWorkspace>{if(!validStore(data))throw new Error('Collection data is invalid; cloud save cancelled.');if(new Blob([JSON.stringify(data)]).size>10*1024*1024)throw new Error('This workspace exceeds the 10 MB sync limit. Export a backup and reduce photo sizes.');const session=await freshSession(config);const result=await request(config,'/rest/v1/rpc/collector_save_workspace',{method:'POST',body:JSON.stringify({new_payload:data,expected_revision:revision})},session.access_token);if(!result?.saved)throw new CloudConflict();return {payload:data,revision:result.revision,updated_at:result.updated_at}}
