export type Identity={sku?:string;collectorNumber?:string;setCode?:string;modelNumber?:string;upc?:string;brand?:string;series?:string;edition?:string;year?:string;language?:string;description?:string;marketCategory?:'other'|'cards'|'comics'|'games';pricechartingId?:string;scryfallId?:string;tcgplayerId?:string;justtcgId?:string;justtcgVariantId?:string;hobbydbId?:string;ebayEpid?:string};
export type Grading={graded:boolean;company:string;grade:string;certification:string;designation:string};
export type PackagingState='sealed'|'opened-box'|'loose';
export type MarketLink={provider:string;query:string;linkedAt:string;lastRefresh?:string};
export type PricePoint={date:string;value:number;variant:string;source:string;url:string;kind:'manual'|'provider'|'sale'};
export type Comparable={id:string;date:string;price:number;shipping:number;currency:'USD';variant:string;source:string;url:string;title:string};
export type MarketItem={name:string;condition:string;packagingState?:PackagingState;marketLink?:MarketLink;identity?:Identity;grading?:Grading};
export function packagingLabel(state?:PackagingState){return state==='sealed'?'Raw · Sealed':state==='opened-box'?'Raw · Opened with box':state==='loose'?'Raw · Opened without box':'Raw / ungraded'}
export function variantKey(item:MarketItem){const g=item.grading;if(g?.graded)return `graded|${g.company.trim().toUpperCase()}|${g.grade.trim()}|${g.designation.trim().toUpperCase()}`;return item.packagingState?`raw|${item.packagingState}|${item.condition}`:`raw|${item.condition}`}
export function variantLabel(item:MarketItem){const g=item.grading;if(g?.graded)return `${g.company} ${g.grade}${g.designation?' · '+g.designation:''}`;return item.packagingState?`${packagingLabel(item.packagingState)}${item.condition?' · '+item.condition:''}`:`Ungraded · ${item.condition}`}
export function marketQuery(item:MarketItem){const i=item.identity||{};return [item.name,i.brand,i.series,i.setCode,i.collectorNumber,i.edition,i.year,i.language,i.sku,i.modelNumber,i.upc,item.grading?.graded?`${item.grading.company} ${item.grading.grade} ${item.grading.designation}`:item.packagingState?packagingLabel(item.packagingState):item.condition].filter(Boolean).join(' ')}
export function priceTier(item:MarketItem):{key:string;label:string;exactGrade:boolean}|null{const category=item.identity?.marketCategory,g=item.grading?{...item.grading,company:item.grading.company.trim(),grade:/^\d+(\.\d+)?$/.test(item.grading.grade.trim())?String(Number(item.grading.grade)):item.grading.grade.trim(),designation:item.grading.designation.trim()}:undefined;if(!category)return null;if(category==='other'&&!g?.graded){if(item.packagingState==='sealed'||/new|sealed/i.test(item.condition))return {key:'new-price',label:'Raw · sealed',exactGrade:true};if(item.packagingState==='opened-box'||/complete in box|cib/i.test(item.condition))return {key:'cib-price',label:'Raw · opened with box',exactGrade:false};return {key:'loose-price',label:'Raw · opened without box / used',exactGrade:false}}if(category==='other')return null;if(!g?.graded){if(category==='games'){return item.condition==='New / sealed'?{key:'new-price',label:'New / sealed',exactGrade:true}:item.condition==='Complete in box'?{key:'cib-price',label:'Complete in box',exactGrade:true}:{key:'loose-price',label:'Loose / used',exactGrade:false}}return {key:'loose-price',label:'Ungraded',exactGrade:false}}
if(category==='cards'){const exact:Record<string,string>={'PSA|10|':'manual-only-price','BGS|10|':'bgs-10-price','CGC|10|':'condition-17-price','SGC|10|':'condition-18-price','CGC|10|PRISTINE':'condition-19-price','BGS|10|BLACK LABEL':'condition-20-price','TAG|10|':'condition-21-price','ACE|10|':'condition-22-price'};const key=exact[`${g.company.toUpperCase()}|${g.grade}|${g.designation.toUpperCase()}`];if(key)return {key,label:variantLabel(item),exactGrade:true};if(g.designation)return null;const generic:Record<string,string>={'1':'condition-9-price','2':'condition-10-price','3':'condition-13-price','4':'condition-14-price','5':'condition-15-price','6':'condition-16-price','7':'cib-price','7.5':'cib-price','8':'new-price','8.5':'new-price','9':'graded-price','9.5':'box-only-price'};return generic[g.grade]?{key:generic[g.grade],label:`Grade ${g.grade} · pooled grading companies${['7','7.5','8','8.5'].includes(g.grade)?' / paired grades':''}`,exactGrade:false}:null}
if(category==='comics'&&!g.designation){const keys:Record<string,string>={'2':'condition-9-price','2.0':'condition-9-price','3':'condition-13-price','3.0':'condition-13-price','4':'cib-price','4.0':'cib-price','4.5':'cib-price','5':'condition-14-price','5.0':'condition-14-price','6':'new-price','6.0':'new-price','6.5':'new-price','7':'condition-15-price','7.0':'condition-15-price','8':'graded-price','8.0':'graded-price','8.5':'graded-price','9':'condition-16-price','9.0':'condition-16-price','9.2':'box-only-price','9.4':'condition-17-price','9.6':'condition-10-price','9.8':'manual-only-price','10':'bgs-10-price','10.0':'bgs-10-price'};return keys[g.grade]?{key:keys[g.grade],label:`Comic grade ${g.grade} · pooled grading companies`,exactGrade:false}:null}return null}
export function medianSale(comps:Comparable[],variant:string){const values=comps.filter(c=>c.variant===variant&&c.currency==='USD').map(c=>c.price+c.shipping).sort((a,b)=>a-b);if(!values.length)return null;const middle=Math.floor(values.length/2);return values.length%2?values[middle]:(values[middle-1]+values[middle])/2}
export function identityKey(item:MarketItem){return JSON.stringify([item.name,item.identity?.sku||'',item.identity?.collectorNumber||'',item.identity?.setCode||'',item.identity?.modelNumber||'',item.identity?.upc||'',item.identity?.brand||'',item.identity?.series||'',item.identity?.edition||'',item.identity?.year||'',item.identity?.language||'',item.identity?.marketCategory||'',item.identity?.pricechartingId||'',item.identity?.scryfallId||'',item.identity?.tcgplayerId||'',item.identity?.justtcgId||'',item.identity?.justtcgVariantId||'',item.identity?.hobbydbId||'',item.identity?.ebayEpid||''])}
export function averageRecentSales(comps:Comparable[],variant:string,limit=10){const values=comps.filter(c=>c.variant===variant&&c.currency==='USD').toSorted((a,b)=>b.date.localeCompare(a.date)).slice(0,limit).map(c=>c.price+c.shipping);if(!values.length)return null;return values.reduce((sum,n)=>sum+n,0)/values.length}
