import {Identity,Grading,PricePoint,Comparable,variantKey} from './market';
export type Status = 'owned' | 'wishlist' | 'sold';
export type Collection = {id:string; name:string; icon:string; color:string; logo?:string};
export type Item = {identity?:Identity; grading?:Grading; priceHistory?:PricePoint[]; comparables?:Comparable[]; id:string; collectionId:string; name:string; category:string; status:Status; purchasePrice:number; currentValue:number; quantity:number; image:string; condition:string; purchaseDate:string; location:string; notes:string; customFields:Record<string,string>; createdAt:string; updatedAt:string};
export type ValueSnapshot = {date:string; values:Record<string,number>};
export type Preferences={accentColor:string;density:'comfortable'|'compact';cardSize:'standard'|'large';reducedMotion:boolean};
export type Store = {version:1; collections:Collection[]; items:Item[]; profile?:{name:string; image:string}; preferences?:Preferences; history?:ValueSnapshot[]};
export const money = (n:number) => new Intl.NumberFormat('en-US',{style:'currency',currency:'USD',minimumFractionDigits:2,maximumFractionDigits:2}).format(n);
export function recordValue(data:Store):Store {const values:Record<string,number>={};for(const c of data.collections)values[c.id]=data.items.filter(i=>i.collectionId===c.id&&i.status==='owned').reduce((sum,i)=>sum+i.currentValue*i.quantity,0);const date=new Date().toISOString();const day=date.slice(0,10);const history=[...(data.history||[])];const last=history.at(-1);if(last?.date.slice(0,10)===day){history[history.length-1]={date,values}}else history.push({date,values});const items=data.items.map(item=>{const variant=variantKey(item);const points=item.priceHistory||[];const latest=points.filter(p=>p.variant===variant&&p.kind!=='sale').at(-1);if(latest&&latest.date.slice(0,10)===day&&latest.value===item.currentValue)return item;return {...item,priceHistory:[...points,{date,value:item.currentValue,variant,source:'Manually entered',url:'',kind:'manual' as const}].slice(-3000)}});return {...data,items,history:history.slice(-1500)}}
export function widgetSnapshot(data:Store,collectionId?:string) {const items=data.items.filter(i=>i.status==='owned'&&(!collectionId||i.collectionId===collectionId));return {updatedAt:new Date().toISOString(),itemCount:items.reduce((n,i)=>n+i.quantity,0),totalValue:items.reduce((n,i)=>n+i.currentValue*i.quantity,0),recent:items.toSorted((a,b)=>b.createdAt.localeCompare(a.createdAt)).slice(0,4),mostValuable:items.toSorted((a,b)=>b.currentValue-a.currentValue).slice(0,4)};}
export function validStore(value:unknown):value is Store {if(!value||typeof value!=='object')return false;const s=value as Store;return (!s.profile||(typeof s.profile.name==='string'&&typeof s.profile.image==='string'))&&(!s.preferences||(typeof s.preferences.accentColor==='string'&&/^#[0-9a-f]{6}$/i.test(s.preferences.accentColor)&&['comfortable','compact'].includes(s.preferences.density)&&['standard','large'].includes(s.preferences.cardSize)&&typeof s.preferences.reducedMotion==='boolean'))&&(!s.history||(Array.isArray(s.history)&&s.history.every(h=>h&&typeof h.date==='string'&&Number.isFinite(Date.parse(h.date))&&!!h.values&&typeof h.values==='object'&&!Array.isArray(h.values)&&Object.values(h.values).every(v=>typeof v==='number'&&Number.isFinite(v)&&v>=0))))&&s.version===1&&Array.isArray(s.collections)&&Array.isArray(s.items)&&s.collections.every(c=>c&&typeof c.id==='string'&&typeof c.name==='string'&&typeof c.icon==='string'&&typeof c.color==='string'&&(c.logo===undefined||typeof c.logo==='string'))&&new Set(s.collections.map(c=>c.id)).size===s.collections.length&&s.items.every(i=>i&&validMarketFields(i)&&typeof i.id==='string'&&typeof i.name==='string'&&s.collections.some(c=>c.id===i.collectionId)&&['owned','wishlist','sold'].includes(i.status)&&[i.purchasePrice,i.currentValue,i.quantity].every(n=>typeof n==='number'&&Number.isFinite(n)&&n>=0)&&Number.isInteger(i.quantity)&&i.quantity>=1&&['image','category','condition','purchaseDate','location','notes','createdAt','updatedAt'].every(k=>typeof (i as unknown as Record<string,unknown>)[k]==='string')&&!!i.customFields&&typeof i.customFields==='object'&&!Array.isArray(i.customFields)&&Object.values(i.customFields).every(v=>typeof v==='string'))&&new Set(s.items.map(i=>i.id)).size===s.items.length;}

function validMarketFields(item:Item){return (!item.identity||(typeof item.identity==='object'&&!Array.isArray(item.identity)&&Object.values(item.identity).every(v=>typeof v==='string')&&(!item.identity.marketCategory||['other','cards','comics','games'].includes(item.identity.marketCategory))))&&(!item.grading||(typeof item.grading.graded==='boolean'&&['company','grade','certification','designation'].every(k=>typeof (item.grading as unknown as Record<string,unknown>)[k]==='string')))&&(!item.priceHistory||(Array.isArray(item.priceHistory)&&item.priceHistory.every(p=>p&&Number.isFinite(Date.parse(p.date))&&typeof p.value==='number'&&Number.isFinite(p.value)&&p.value>=0&&['variant','source','url'].every(k=>typeof (p as unknown as Record<string,unknown>)[k]==='string')&&['manual','provider','sale'].includes(p.kind))))&&(!item.comparables||(Array.isArray(item.comparables)&&item.comparables.every(c=>c&&typeof c.id==='string'&&/^\d{4}-\d{2}-\d{2}$/.test(c.date)&&Number.isFinite(Date.parse(c.date))&&[c.price,c.shipping].every(n=>typeof n==='number'&&Number.isFinite(n)&&n>=0)&&c.currency==='USD'&&['variant','source','url','title'].every(k=>typeof (c as unknown as Record<string,unknown>)[k]==='string')&&/^https?:\/\//.test(c.url))))}

