'use client';
import {useCallback,useEffect,useRef,useState} from 'react';
import {demo} from './demo';
import {Store,recordValue,validStore} from './model';
import {CloudConfig,CloudWorkspace,Session,CloudConflict,cloudConfig,restoreSession,loadWorkspace,saveWorkspace,logout,hasInlineWorkspaceImages,externalizeWorkspaceImages} from './cloud';
export const LOCAL_KEY='shelf.collection.v1';
const LOCAL_EVENT='vexum.workspace.local';
type Cache={data:Store;revision:number;pending:boolean};
export const emptyWorkspace:Store={version:1,collections:[],items:[]};
export function useWorkspace(){const [data,setView]=useState<Store>(demo),[ready,setReady]=useState(false),[config,setConfig]=useState<CloudConfig|null>(null),[session,setSession]=useState<Session|null>(null),[revision,setRevision]=useState(0),[status,setStatus]=useState('Loading…'),[error,setError]=useState(''),[needsMigration,setMigration]=useState(false),[conflict,setConflict]=useState(false),[busy,setBusy]=useState(false),[tick,setTick]=useState(0);const current=useRef(data),pending=useRef(false),sessionRef=useRef<Session|null>(null),rev=useRef(0),blocked=useRef(false),writing=useRef(false),optimizing=useRef(false),remote=useRef<CloudWorkspace|null>(null),local=useRef<Store>(demo);
function display(next:Store){current.current=next;setView(next)}
function persist(next:Store,pendingFlag:boolean){try{if(sessionRef.current)localStorage.setItem('collector.cloud.'+sessionRef.current.user.id,JSON.stringify({data:next,revision:rev.current,pending:pendingFlag}));else localStorage.setItem(LOCAL_KEY,JSON.stringify(next));return true}catch{setError('Device storage is full. Download a backup; some changes may not survive closing this browser.');return false}}
useEffect(()=>{let alive=true;async function initialize(){let localData=demo;try{const saved=localStorage.getItem(LOCAL_KEY);if(saved){const parsed=JSON.parse(saved);if(!validStore(parsed))throw new Error('Local collection cannot be read. Restore a backup before editing.');localData=parsed}}catch(err){blocked.current=true;setError(err instanceof Error?err.message:'Unable to read saved collection.')}local.current=localData;display(recordValue(localData));try{const cfg=await cloudConfig();if(!alive)return;setConfig(cfg);if(!cfg.configured){setStatus('Local mode');return}const auth=await restoreSession(cfg);if(!alive)return;if(!auth){setStatus('Local mode');return}sessionRef.current=auth;setSession(auth);let cache:Cache|null=null;try{const saved=localStorage.getItem('collector.cloud.'+auth.user.id);if(saved){const parsed=JSON.parse(saved);if(validStore(parsed.data)&&Number.isInteger(parsed.revision)&&parsed.revision>=0&&typeof parsed.pending==='boolean')cache=parsed}}catch{}
const row=await loadWorkspace(cfg);if(!alive)return;remote.current=row;rev.current=row?.revision||0;setRevision(rev.current);if(cache?.pending){display(cache.data);pending.current=true;if(cache.revision!==rev.current){rev.current=cache.revision;setRevision(cache.revision);blocked.current=true;setConflict(true);setStatus('Conflict · edits kept');setError(new CloudConflict().message)}else {if(!row){setMigration(true);setStatus('Ready to migrate')}else{setStatus('Waiting to sync');setTick(t=>t+1)}}}else if(row){const next=recordValue(row.payload);display(next);persist(next,false);setStatus('Cloud synced')}else {
  const next=recordValue(cache?.data||localData);
  try{
    const saved=await saveWorkspace(cfg,next,0);
    rev.current=saved.revision;setRevision(saved.revision);pending.current=false;
    display(next);persist(next,false);setMigration(false);setStatus('Cloud synced');setError('');
  }catch(seedErr){
    const latest=await loadWorkspace(cfg).catch(()=>null);
    if(latest){rev.current=latest.revision;setRevision(latest.revision);const cloudNext=recordValue(latest.payload);display(cloudNext);persist(cloudNext,false);setMigration(false);setStatus('Cloud synced');}
    else {display(next);setMigration(true);setStatus('Ready to migrate');throw seedErr}
  }
}
}catch(err){setError(err instanceof Error?err.message:'Cloud unavailable.');setStatus(sessionRef.current?'Cloud unavailable':'Local mode');if(sessionRef.current){blocked.current=true;try{const saved=localStorage.getItem('collector.cloud.'+sessionRef.current.user.id);if(saved){const cache=JSON.parse(saved);if(validStore(cache.data)){display(cache.data);pending.current=cache.pending;rev.current=cache.revision;setRevision(cache.revision)}}}catch{}}}finally{if(alive)setReady(true)}}initialize();return()=>{alive=false}},[]);
const update=useCallback((next:Store)=>{const recorded=recordValue(next);display(recorded);if(blocked.current&&!sessionRef.current){setError('Saved storage could not be loaded. Export a backup before restoring valid data.');return}if(!sessionRef.current)local.current=recorded;if(sessionRef.current){pending.current=true;setStatus(conflict?'Conflict · edits kept':'Waiting to sync')}persist(recorded,pending.current);try{window.dispatchEvent(new CustomEvent(LOCAL_EVENT,{detail:recorded}))}catch{}},[conflict]);
useEffect(()=>{const receive=(event:Event)=>{const next=(event as CustomEvent).detail;if(next===current.current||!validStore(next))return;display(recordValue(next));if(!sessionRef.current)local.current=next};window.addEventListener(LOCAL_EVENT,receive);return()=>window.removeEventListener(LOCAL_EVENT,receive)},[]);
useEffect(()=>{if(ready&&!session&&!blocked.current)persist(current.current,false)},[ready,session]);
useEffect(()=>{if(!ready||!config?.configured||!session||needsMigration||blocked.current||optimizing.current||!hasInlineWorkspaceImages(current.current))return;let cancelled=false;optimizing.current=true;setStatus('Optimizing photos…');externalizeWorkspaceImages(config,current.current,(done,total)=>{if(!cancelled)setStatus(`Optimizing photos… ${done}/${total}`)}).then(({data:next,migrated})=>{if(cancelled)return;const recorded=recordValue(next);display(recorded);pending.current=true;persist(recorded,true);setError('');setStatus(migrated?`Optimized ${migrated} photo${migrated===1?'':'s'} · waiting to sync`:'Waiting to sync');setTick(t=>t+1)}).catch(err=>{if(!cancelled){setError(err instanceof Error?err.message:'Unable to optimize photos.');setStatus('Photo optimization failed · edits kept')}}).finally(()=>{optimizing.current=false;if(!cancelled)setTick(t=>t+1)});return()=>{cancelled=true}},[data,ready,config,session,needsMigration]);
useEffect(()=>{if(!ready||!config?.configured||!session||needsMigration)return;let cancelled=false;let polling=false;async function check(){if(pending.current||writing.current||blocked.current||polling)return;polling=true;try{const row=await loadWorkspace(config!);if(cancelled||pending.current||writing.current||!row||row.revision<=rev.current)return;rev.current=row.revision;setRevision(row.revision);display(recordValue(row.payload));persist(current.current,false);setStatus('Cloud synced')}catch{}finally{polling=false}}const timer=setInterval(check,30000);window.addEventListener('focus',check);return()=>{cancelled=true;clearInterval(timer);window.removeEventListener('focus',check)}},[ready,config,session,needsMigration]);
useEffect(()=>{if(!ready||!config?.configured||!session||!pending.current||needsMigration||blocked.current||optimizing.current||hasInlineWorkspaceImages(current.current))return;const timer=setTimeout(async()=>{if(writing.current||optimizing.current||hasInlineWorkspaceImages(current.current))return;writing.current=true;setStatus('Syncing…');const snapshot=current.current;try{const saved=await saveWorkspace(config,snapshot,rev.current);rev.current=saved.revision;setRevision(saved.revision);pending.current=current.current!==snapshot;persist(current.current,pending.current);setStatus(pending.current?'Waiting to sync':'Cloud synced');setError('')}catch(err){setError(err instanceof Error?err.message:'Unable to sync.');setStatus('Not synced · edits kept');if(err instanceof CloudConflict){blocked.current=true;setConflict(true);setStatus('Conflict · edits kept')}}finally{writing.current=false;if(pending.current&&!blocked.current)setTimeout(()=>setTick(t=>t+1),15000)}},800);return()=>clearTimeout(timer)},[data,ready,config,session,revision,needsMigration,tick]);
async function migrate(useLocal:boolean){if(!config||!session)return;setBusy(true);try{let next=recordValue(useLocal?current.current:emptyWorkspace);if(hasInlineWorkspaceImages(next)){setStatus('Optimizing photos…');next=recordValue((await externalizeWorkspaceImages(config,next)).data)}const saved=await saveWorkspace(config,next,0);rev.current=saved.revision;setRevision(saved.revision);pending.current=false;display(next);persist(next,false);setMigration(false);setStatus('Cloud synced');setError('')}catch(err){setError(err instanceof Error?err.message:'Migration failed. Your local collection is unchanged.');if(err instanceof CloudConflict)setConflict(true)}finally{setBusy(false)}}
async function refresh(){if(!config||!session)return;setBusy(true);try{const row=await loadWorkspace(config);if(!row){setMigration(true);blocked.current=false;setConflict(false);setError('');return}if(pending.current){localStorage.setItem('collector.conflict-backup.'+session.user.id+'.'+Date.now(),JSON.stringify(current.current))}rev.current=row.revision;setRevision(row.revision);pending.current=false;blocked.current=false;setConflict(false);setMigration(false);const next=recordValue(row.payload);display(next);persist(next,false);setStatus('Cloud synced');setError('')}catch(err){setError(err instanceof Error?err.message:'Unable to reload cloud collection.')}finally{setBusy(false)}}
async function signOut(){if(!config||writing.current)return;setBusy(true);try{await logout(config)}catch{}finally{sessionRef.current=null;setSession(null);blocked.current=false;pending.current=false;setConflict(false);setMigration(false);setError('');rev.current=0;setRevision(0);display(recordValue(local.current));setStatus('Local mode');setBusy(false)}}
useEffect(()=>{if(!ready||!config?.configured||!session||!needsMigration||busy||blocked.current)return;const timer=setTimeout(()=>{migrate(true).catch(()=>{})},1800);return()=>clearTimeout(timer)},[ready,config,session,needsMigration,busy]);
useEffect(()=>{const online=()=>{if(!blocked.current)setTick(t=>t+1)};window.addEventListener('online',online);return()=>window.removeEventListener('online',online)},[]);
return {data,ready,update,config,session,status,error,needsMigration,conflict,busy,migrate,refresh,signOut,retry:()=>{blocked.current=false;setConflict(false);setTick(t=>t+1)},pending:pending.current,recovery:()=>{if(!sessionRef.current)return null;const prefix='collector.conflict-backup.'+sessionRef.current.user.id+'.';const keys=Object.keys(localStorage).filter(key=>key.startsWith(prefix)).sort().reverse();if(!keys.length)return null;try{const recovered=JSON.parse(localStorage.getItem(keys[0])||'null');return validStore(recovered)?recovered:null}catch{return null}},clearStorageBlock:()=>{if(!sessionRef.current)blocked.current=false}}}


