import {NextRequest,NextResponse} from 'next/server';
import {MarketItem,priceTier} from '../../../lib/market';
export const runtime='nodejs';
let lastRequest=0;
export async function GET(){return NextResponse.json({provider:'PriceCharting',connected:!!process.env.PRICECHARTING_TOKEN,historyAvailable:false})}
function sameOrigin(req:NextRequest){const origin=req.headers.get('origin');if(!origin)return true;try{return new URL(origin).host===req.headers.get('host')}catch{return false}}
export async function POST(req:NextRequest){if(!sameOrigin(req))return NextResponse.json({error:'Invalid origin.'},{status:403});let item:MarketItem;try{const body=await req.json();item=body.item;if(!item||typeof item.name!=='string'||item.name.length>200||typeof item.condition!=='string'||(item.identity&&Object.values(item.identity).some(v=>typeof v!=='string'||v.length>2000))||(item.grading&&(typeof item.grading.graded!=='boolean'||['company','grade','certification','designation'].some(k=>typeof (item.grading as unknown as Record<string,unknown>)[k]!=='string'))))throw new Error()}catch{return NextResponse.json({error:'Invalid item details.'},{status:400})}
const token=process.env.PRICECHARTING_TOKEN;if(!token)return NextResponse.json({error:'PriceCharting is not connected. Add its API token to the local server configuration to enable lookups.',code:'not_connected'},{status:503});const tier=priceTier(item);if(!tier)return NextResponse.json({error:'No supported price tier for this category, grading company, grade or designation. Use verified sold comparisons for this version.'},{status:422});const now=Date.now();if(now-lastRequest<1200)return NextResponse.json({error:'Please wait a moment before another lookup.'},{status:429});lastRequest=now;const i=item.identity||{};const params=new URLSearchParams({t:token});if(i.pricechartingId){if(!/^\d+$/.test(i.pricechartingId))return NextResponse.json({error:'PriceCharting product ID must be numeric.'},{status:400});params.set('id',i.pricechartingId)}else if(i.upc)params.set('upc',i.upc);else params.set('q',[item.name,i.brand,i.series,i.edition,i.year,i.language,i.sku,i.modelNumber,i.description?.slice(0,500)].filter(Boolean).join(' '));try{const response=await fetch('https://www.pricecharting.com/api/product?'+params,{cache:'no-store',signal:AbortSignal.timeout(12000)});if(!response.ok)return NextResponse.json({error:'The price provider could not complete this request. Check your connection and subscription.'},{status:502});const product=await response.json();if(product.status!=='success'||!product.id)return NextResponse.json({error:'No matching product returned. Try a provider product ID or a more specific name.'},{status:404});const cents=product[tier.key];if(cents===undefined||cents===null||cents===''||!Number.isFinite(Number(cents))||Number(cents)<=0)return NextResponse.json({error:'This provider has no price for the selected version.'},{status:404});const exactIdentifier=!!((i.pricechartingId&&String(product.id)===i.pricechartingId)||(i.upc&&String(product.upc)===i.upc));return NextResponse.json({productId:String(product.id),name:String(product['product-name']||''),series:String(product['console-name']||''),upc:String(product.upc||''),value:Number(cents)/100,tier:tier.label,exactGrade:tier.exactGrade,match:exactIdentifier?'identifier':'description',source:'PriceCharting',url:'https://www.pricecharting.com/search-products?'+new URLSearchParams({q:String(product['product-name']||item.name),type:'prices'}),fetchedAt:new Date().toISOString(),warning:'Check edition, language, condition and grading designation before applying. Provider values are estimates, not guaranteed sale prices.'})}catch{return NextResponse.json({error:'Market lookup timed out or is unavailable. Your saved value has not changed.'},{status:502})}}


