import {NextRequest,NextResponse} from 'next/server';
import {MarketItem,priceTier} from '../../../lib/market';
export const runtime='nodejs';
let lastPriceChartingRequest=0;
type RichMarketItem=MarketItem&{category?:string;customFields?:Record<string,string>};
function sameOrigin(req:NextRequest){const origin=req.headers.get('origin');if(!origin)return true;try{return new URL(origin).host===req.headers.get('host')}catch{return false}}
function clean(value:string|undefined){return (value||'').trim()}
function norm(value:string|undefined){return clean(value).toLowerCase().replace(/[’']/g,"'").replace(/[^a-z0-9]+/g,' ').trim()}
function magicName(value:string){return value.replace(/\s+\((?:borderless|showcase|extended art|retro frame|surge foil|serialized|foil etched)\)\s*$/i,'').trim()}
function isMagic(item:RichMarketItem){const brand=norm(item.identity?.brand),category=norm(item.category);return brand.includes('magic the gathering')||category.includes('magic the gathering')}
function overlapScore(a:string,b:string){const aa=new Set(norm(a).split(' ').filter(x=>x.length>2)),bb=new Set(norm(b).split(' ').filter(x=>x.length>2));let n=0;for(const x of aa)if(bb.has(x))n++;return n}
async function scryfallLookup(item:RichMarketItem){if(!isMagic(item))return null;const i=item.identity||{};const targetName=magicName(item.name),collector=clean(i.collectorNumber||item.customFields?.['Card #']||i.sku),setLabel=clean(i.series||item.customFields?.Set),wantFoil=/foil/i.test(clean(i.edition)||clean(item.customFields?.Finish));const headers={'User-Agent':'CollectorApp/1.0 (+https://collector-five-ecru.vercel.app)','Accept':'application/json;q=0.9,*/*;q=0.8'};let cards:any[]=[];const terms=[`!\"${targetName.replace(/\"/g,'')}\"`,collector?`cn:\"${collector.replace(/\"/g,'')}\"`:''].filter(Boolean).join(' ');try{const u='https://api.scryfall.com/cards/search?'+new URLSearchParams({q:terms,unique:'prints',order:'released'});const r=await fetch(u,{headers,cache:'no-store',signal:AbortSignal.timeout(10000)});if(r.ok){const j=await r.json();cards=Array.isArray(j.data)?j.data:[]}}catch{}
if(!cards.length){try{const u='https://api.scryfall.com/cards/named?'+new URLSearchParams({fuzzy:targetName});const r=await fetch(u,{headers,cache:'no-store',signal:AbortSignal.timeout(10000)});if(r.ok)cards=[await r.json()]}catch{}}
if(!cards.length)return null;const scored=cards.map(card=>{let score=0;if(norm(card.name)===norm(targetName))score+=6;if(collector&&String(card.collector_number||'')===collector)score+=5;if(setLabel)score+=Math.min(4,overlapScore(String(card.set_name||''),setLabel));if(i.setCode&&norm(card.set)===norm(i.setCode))score+=6;if(wantFoil&&card.prices?.usd_foil)score+=2;if(!wantFoil&&card.prices?.usd)score+=2;return {card,score}}).sort((a,b)=>b.score-a.score);const {card,score}=scored[0];const rawPrice=wantFoil?(card.prices?.usd_foil||card.prices?.usd):(card.prices?.usd||card.prices?.usd_foil);const value=Number(rawPrice);if(!Number.isFinite(value)||value<=0)return null;const collectorMatch=!!collector&&String(card.collector_number||'')===collector;const setMatch=!!setLabel&&overlapScore(String(card.set_name||''),setLabel)>=2;const confidence=Math.min(.99,collectorMatch&&setMatch ? .97 : collectorMatch ? .9 : score>=8 ? .86 : .72);return {productId:String(card.id||''),name:String(card.name||item.name),series:String(card.set_name||''),upc:'',value,tier:wantFoil?'Foil market price':'Market price',exactGrade:!item.grading?.graded,match:collectorMatch?'identifier':'description',confidence,source:'Scryfall',url:String(card.scryfall_uri||'https://scryfall.com'),fetchedAt:new Date().toISOString(),warning:'Scryfall is a current card-market reference, not a last-10-sold feed. Verify set, collector number and finish before relying on the estimate.',identifiers:{scryfallId:String(card.id||''),setCode:String(card.set||''),collectorNumber:String(card.collector_number||collector||'')}}}
export async function GET(){return NextResponse.json({provider:'Multi-source',connected:true,historyAvailable:false,providers:{scryfall:true,priceCharting:!!process.env.PRICECHARTING_TOKEN}})}
export async function POST(req:NextRequest){if(!sameOrigin(req))return NextResponse.json({error:'Invalid origin.'},{status:403});let item:RichMarketItem;try{const body=await req.json();item=body.item;if(!item||typeof item.name!=='string'||item.name.length>200||typeof item.condition!=='string'||(item.identity&&Object.values(item.identity).some(v=>typeof v!=='string'||v.length>2000))||(item.grading&&(typeof item.grading.graded!=='boolean'||['company','grade','certification','designation'].some(k=>typeof (item.grading as unknown as Record<string,unknown>)[k]!=='string'))))throw new Error()}catch{return NextResponse.json({error:'Invalid item details.'},{status:400})}
const scryfall=await scryfallLookup(item);if(scryfall)return NextResponse.json(scryfall);
const token=process.env.PRICECHARTING_TOKEN;if(!token)return NextResponse.json({error:'No automatic provider is connected for this item yet. Magic cards can use Scryfall automatically; other categories need a PriceCharting token or verified sold comparisons.',code:'not_connected'},{status:503});const tier=priceTier(item);if(!tier)return NextResponse.json({error:'No supported price tier for this category, grading company, grade or designation. Use verified sold comparisons for this version.'},{status:422});const now=Date.now();if(now-lastPriceChartingRequest<1200)return NextResponse.json({error:'Please wait a moment before another lookup.'},{status:429});lastPriceChartingRequest=now;const i=item.identity||{};const params=new URLSearchParams({t:token});if(i.pricechartingId){if(!/^\d+$/.test(i.pricechartingId))return NextResponse.json({error:'PriceCharting product ID must be numeric.'},{status:400});params.set('id',i.pricechartingId)}else if(i.upc)params.set('upc',i.upc);else params.set('q',[item.name,i.brand,i.series,i.setCode,i.collectorNumber,i.edition,i.year,i.language,i.sku,i.modelNumber,i.description?.slice(0,500)].filter(Boolean).join(' '));try{const response=await fetch('https://www.pricecharting.com/api/product?'+params,{cache:'no-store',signal:AbortSignal.timeout(12000)});if(!response.ok)return NextResponse.json({error:'The price provider could not complete this request. Check your connection and subscription.'},{status:502});const product=await response.json();if(product.status!=='success'||!product.id)return NextResponse.json({error:'No matching product returned. Try a provider product ID or a more specific name.'},{status:404});const cents=product[tier.key];if(cents===undefined||cents===null||cents===''||!Number.isFinite(Number(cents))||Number(cents)<=0)return NextResponse.json({error:'This provider has no price for the selected version.'},{status:404});const exactIdentifier=!!((i.pricechartingId&&String(product.id)===i.pricechartingId)||(i.upc&&String(product.upc)===i.upc));return NextResponse.json({productId:String(product.id),name:String(product['product-name']||''),series:String(product['console-name']||''),upc:String(product.upc||''),value:Number(cents)/100,tier:tier.label,exactGrade:tier.exactGrade,match:exactIdentifier?'identifier':'description',confidence:exactIdentifier?.98:.76,source:'PriceCharting',url:'https://www.pricecharting.com/search-products?'+new URLSearchParams({q:String(product['product-name']||item.name),type:'prices'}),fetchedAt:new Date().toISOString(),warning:'PriceCharting returns a current guide value, not a last-10-sold feed. Check edition, language, condition and grading designation before applying.',identifiers:{pricechartingId:String(product.id)}})}catch{return NextResponse.json({error:'Market lookup timed out or is unavailable. Your saved value has not changed.'},{status:502})}}
