'use client';
import {useCallback,useEffect,useRef,useState,type ReactNode,type PointerEvent,type CSSProperties} from 'react';
import {Plus,SlidersHorizontal,Check,GripVertical,X,Search,Undo2,ArrowUp,ArrowDown,ArrowLeft,ArrowRight,LayoutGrid} from 'lucide-react';
import widgets from './widgets.json';
import {packHomeWidgets,pinHomeLayout,moveHomeWidget} from './widget-layout';
import type {WidgetPlacement} from '../../lib/platform';
import {VexumDialog} from '../VexumUi';
const name=(id:string)=>widgets.find(w=>w.id===id)?.name.split(' / ').at(-1)||'Widget';
const categories=['All','Collection','Money','Life','Setup','Social'];
function category(title:string){return /Rep|Social|Post|Follower/.test(title)?'Social':/Setup|Space|Shelf|Spot/.test(title)?'Setup':/Calendar|Task|Today|Focus|Habit|Goal Progress|Workout|Daily Note|Upcoming|Next Up/.test(title)?'Life':/Spend|Budget|Debt|Bill|Cash|Savings|Revenue|Profit|Payout|Net Worth/.test(title)?'Money':'Collection'}
type Props={width:number;layouts:WidgetPlacement[];onChange:(rows:WidgetPlacement[])=>void;renderWidget:(id:string,preview?:boolean)=>ReactNode;libraryRequest:number};
export default function ControlCenter({width,layouts,onChange,renderWidget,libraryRequest}:Props){
 const [draft,setDraft]=useState<WidgetPlacement[]|null>(null),[library,setLibrary]=useState(false),[query,setQuery]=useState(''),[filter,setFilter]=useState('All'),[selected,setSelected]=useState<string|null>(null),[announcement,setAnnouncement]=useState(''),[history,setHistory]=useState<WidgetPlacement[][]>([]);
 const [drag,setDrag]=useState<{id:string;dx:number;dy:number}|null>(null);
 const pointer=useRef<{id:string;pointerId:number;startX:number;startY:number;scroll:number;before:WidgetPlacement[];x:number;y:number}|null>(null),area=useRef<HTMLDivElement>(null),addButton=useRef<HTMLButtonElement>(null),editButton=useRef<HTMLButtonElement>(null),draftRef=useRef(draft),scrollFrame=useRef(0),lastPointer=useRef({x:0,y:0});
 draftRef.current=draft;
 const rows=draft||layouts,packed=packHomeWidgets(width,rows),editing=!!draft;
 useEffect(()=>{if(libraryRequest)setLibrary(true)},[libraryRequest]);
 useEffect(()=>()=>cancelAnimationFrame(scrollFrame.current),[]);
 const closeLibrary=useCallback(()=>{setLibrary(false);requestAnimationFrame(()=>addButton.current?.focus())},[]);
 const saveRows=(next:WidgetPlacement[])=>{if(draft)setDraft(next);else onChange(next)};
 function begin(){setDraft(pinHomeLayout(width,layouts));setHistory([]);setSelected(null);setAnnouncement('Edit mode. Drag a widget or focus its move handle and use arrow keys.');}
 function end(save:boolean){if(save&&draft)onChange(draft);setDraft(null);setSelected(null);setDrag(null);pointer.current=null;cancelAnimationFrame(scrollFrame.current);setAnnouncement(save?'Layout saved.':'Changes discarded.');requestAnimationFrame(()=>editButton.current?.focus());}
 function record(){if(draft)setHistory(h=>[...h.slice(-19),draft]);}
 function toggle(id:string){record();const pinned=pinHomeLayout(width,rows);saveRows(pinHomeLayout(width,pinned.map(w=>w.id===id?{...w,visible:!w.visible}:w)));setAnnouncement((rows.find(w=>w.id===id)?.visible?'Removed ':'Added ')+name(id));}
 function move(id:string,x:number,y:number){const source=draftRef.current;if(!source)return;setDraft(moveHomeWidget(width,source,id,x,y));setAnnouncement(name(id)+', column '+(x+1)+', row '+(y+1)+'.');}
 function updatePointer(clientX:number,clientY:number){const p=pointer.current;if(!p)return;const dy=clientY-p.startY+window.scrollY-p.scroll,dx=clientX-p.startX;setDrag({id:p.id,dx,dy});const item=packHomeWidgets(width,p.before).items.find(w=>w.id===p.id);if(!item)return;const x=Math.max(0,Math.min(packed.columns-item.span,Math.round(item.left/packed.stepX+dx/packed.stepX))),y=Math.max(0,Math.min(200,Math.round(item.top/packed.stepY+dy/packed.stepY)));if(p.x!==x||p.y!==y){p.x=x;p.y=y;setDraft(moveHomeWidget(width,p.before,p.id,x,y));}}
 function start(event:PointerEvent<HTMLButtonElement>,id:string){if(event.button!==0||!draft)return;event.preventDefault();event.currentTarget.focus();event.currentTarget.setPointerCapture(event.pointerId);const item=packed.items.find(w=>w.id===id)!;pointer.current={id,pointerId:event.pointerId,startX:event.clientX,startY:event.clientY,scroll:window.scrollY,before:draft,x:item.x,y:item.y};setSelected(id);setDrag({id,dx:0,dy:0});lastPointer.current={x:event.clientX,y:event.clientY};
  const tick=()=>{if(!pointer.current)return;const y=lastPointer.current.y;if(y>window.innerHeight-64)window.scrollBy(0,12);else if(y<80)window.scrollBy(0,-12);updatePointer(lastPointer.current.x,y);scrollFrame.current=requestAnimationFrame(tick)};scrollFrame.current=requestAnimationFrame(tick);
 }
 function finish(cancel=false){const p=pointer.current;if(!p)return;cancelAnimationFrame(scrollFrame.current);if(cancel)setDraft(p.before);else setHistory(h=>[...h.slice(-19),p.before]);setAnnouncement(cancel?'Move cancelled.':name(p.id)+' placed at column '+(p.x+1)+', row '+(p.y+1)+'.');pointer.current=null;setDrag(null);}
 const selectedItem=packed.items.find(w=>w.id===selected);
 const shown=widgets.filter(w=>(filter==='All'||category(name(w.id))===filter)&&w.name.toLowerCase().includes(query.toLowerCase()));
 return <div className={'vxc-center'+(editing?' is-editing':'')}>
  <div className="vxc-actions"><button ref={addButton} onClick={()=>setLibrary(true)}><Plus size={16}/>Add Widgets</button><button ref={editButton} aria-pressed={editing} onClick={()=>editing?end(true):begin()} className={editing?'primary':''}>{editing?<Check size={16}/>:<SlidersHorizontal size={16}/>} {editing?'Done editing':'Edit Widgets'}</button></div>
  <p className="vxc-sr" aria-live="polite" role="status">{announcement}</p>
  {editing&&<div className="vxc-editor"><div className="vxc-editor-intro"><span className="vxc-editor-icon"><LayoutGrid size={20}/></span><div><strong>Your space. Your layout.</strong><p>Drag to move. Leave room wherever you like.</p></div></div><div className="vxc-editor-buttons"><button disabled={!history.length} onClick={()=>{setDraft(history.at(-1)!);setHistory(h=>h.slice(0,-1));setAnnouncement('Last change undone.')}}><Undo2 size={16}/>Undo</button><button onClick={()=>end(false)}>Cancel</button><button className="primary" onClick={()=>end(true)}><Check size={16}/>Save layout</button></div></div>}
  {editing&&<div className="vxc-placement"><span>{selectedItem?name(selectedItem.id):'Select a widget to fine-tune its position'}</span>{selectedItem&&<><div className="vxc-nudge">{[[ArrowLeft,-1,0,'left'],[ArrowUp,0,-1,'up'],[ArrowDown,0,1,'down'],[ArrowRight,1,0,'right']].map(([Icon,x,y,label])=>{const Component=Icon as typeof ArrowLeft;return <button key={String(label)} aria-label={'Move selected widget '+label} onClick={()=>{record();move(selectedItem.id,Math.max(0,Math.min(packed.columns-selectedItem.span,selectedItem.x+Number(x))),Math.max(0,selectedItem.y+Number(y)))}}><Component size={16}/></button>})}</div><label>Size<select aria-label="Selected widget size" value={selectedItem.span} onChange={e=>{record();saveRows(pinHomeLayout(width,rows.map(w=>w.id===selectedItem.id?{...w,config:{...w.config,span:Number(e.target.value)}}:w),selectedItem.id));}}>{[1,2,4].filter(n=>n<=packed.columns).map(n=><option key={n} value={n}>{n===1?'Small':n===2?'Medium':'Large'}</option>)}</select></label></>}</div>}
  <div ref={area} className="vxc-grid" aria-label="Your widget layout" style={{height:editing?Math.max(500,packed.height+packed.stepY*4):packed.height,'--cell-x':packed.stepX+'px','--cell-y':packed.stepY+'px'} as CSSProperties}>
   {drag&&(()=>{const p=packed.items.find(w=>w.id===drag.id)!;return <div className="vxc-drop-target" style={{width:p.renderedWidth,height:p.renderedHeight,transform:`translate(${p.left}px,${p.top}px)`}}/>})()}
   {packed.items.map(w=>{const active=drag?.id===w.id;const original=active&&pointer.current?packHomeWidgets(width,pointer.current.before).items.find(p=>p.id===w.id):null;return <section key={w.id} data-widget-id={w.id} data-column={w.x} data-row={w.y} aria-label={name(w.id)} className={'vxc-widget'+(active?' is-dragging':'')+(selected===w.id&&editing?' is-selected':'')} style={{width:w.renderedWidth,height:w.renderedHeight,transform:`translate(${active&&original?original.left+drag.dx:w.left}px,${active&&original?original.top+drag.dy:w.top}px)`,zIndex:active?10:1}}>
    <div className="vxc-widget-clip" inert={editing} style={{borderRadius:9.216*w.scale}}><div style={{width:w.width,height:w.height,transform:'scale('+w.scale+')',transformOrigin:'top left'}}>{renderWidget(w.id)}</div></div>
    {editing&&<><button className="vxc-drag-surface" aria-label={'Move '+name(w.id)} aria-describedby="vxc-drag-help" onFocus={()=>setSelected(w.id)} onPointerDown={e=>start(e,w.id)} onPointerMove={e=>{if(pointer.current){lastPointer.current={x:e.clientX,y:e.clientY};updatePointer(e.clientX,e.clientY)}}} onPointerUp={()=>finish()} onPointerCancel={()=>finish(true)} onLostPointerCapture={()=>{if(pointer.current)finish(true)}} onKeyDown={e=>{if(e.key==='Escape'){e.preventDefault();finish(true);return}const dirs:Record<string,number[]>={ArrowLeft:[-1,0],ArrowRight:[1,0],ArrowUp:[0,-1],ArrowDown:[0,1]};if(dirs[e.key]){e.preventDefault();record();move(w.id,Math.max(0,Math.min(packed.columns-w.span,w.x+dirs[e.key][0])),Math.max(0,w.y+dirs[e.key][1]));}}}><span><GripVertical size={15}/>{name(w.id)}</span></button><button className="vxc-remove" aria-label={'Remove '+name(w.id)+' from Home'} onClick={()=>toggle(w.id)}><X size={14}/></button></>}
   </section>})}
   {editing&&<p id="vxc-drag-help" className="vxc-grid-hint">Drag anywhere on a widget. Use arrow keys for precise placement. Empty spaces stay empty.</p>}
  </div>
  {!packed.items.length&&!editing&&<div className="vxc-empty"><LayoutGrid size={32}/><h2>Make room for what matters.</h2><p>Add a few widgets to build your own control center.</p><button className="primary" onClick={()=>setLibrary(true)}><Plus size={16}/>Find your first widget</button></div>}
  <VexumDialog open={library} onClose={closeLibrary} title="Make Home yours" description="A little more focus. A little less noise. Choose what belongs here." size="lg" className="vxc-library" footer={<div className="vxc-library-footer"><span aria-live="polite">{packed.items.length} widgets on Home{editing?' · Unsaved changes':''}</span><button className="primary" onClick={closeLibrary}><Check size={16}/>Done</button></div>}>
   <div className="vxc-search"><Search size={18}/><input autoFocus aria-label="Find widgets" placeholder="Find a widget…" value={query} onChange={e=>setQuery(e.target.value)}/>{query&&<button aria-label="Clear widget search" onClick={()=>setQuery('')}><X size={16}/></button>}</div>
   <div className="vxc-filters" aria-label="Widget categories">{categories.map(c=><button key={c} aria-pressed={c===filter} onClick={()=>setFilter(c)}>{c}</button>)}</div>
   <div className="vxc-library-grid">{shown.map(w=>{const added=rows.find(r=>r.id===w.id)?.visible;return <div className={'vxc-library-card'+(added?' added':'')} key={w.id}><div className="vxc-mini vxf-home" aria-hidden="true" inert><div style={{width:w.width,height:w.height,transform:`scale(${Math.min(232/w.width,106/w.height)})`,transformOrigin:'top left'}}>{renderWidget(w.id,true)}</div></div><button className="vxc-card-label" aria-label={(added?'Remove ':'Add ')+name(w.id)+' '+w.name.split(' / ')[1]} aria-pressed={added} onClick={()=>toggle(w.id)}><div><strong>{name(w.id)}</strong><small>{category(name(w.id))} · {w.name.split(' / ')[1]}</small></div><span>{added?<Check size={18}/>:<Plus size={18}/>}</span></button></div>})}</div>
   {!shown.length&&<div className="vxc-library-empty"><Search size={28}/><h3>No widgets found</h3><p>Try a different name or category.</p><button onClick={()=>{setQuery('');setFilter('All')}}>Clear filters</button></div>}
  </VexumDialog>
 </div>;
}
